#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Генератор data/a1.json из компактных списков слов по темам.
Держим здесь как инструмент для будущего наполнения a2.json, a3.json и т.д. —
движок (index.html) этот файл не использует и не требует его на рантайме.
Запуск: python3 tools/gen_a1.py
"""
import json, os

# (topic_id, title_ru, [grammar_ids], [(en, ru, pos, exampleEn, exampleRu), ...])
TOPICS = [
("greetings", "Приветствие и знакомство", ["g_001"], [
    ("hello", "привет", "interjection", "Hello! My name is Anna.", "Привет! Меня зовут Анна."),
    ("hi", "привет (неформ.)", "interjection", "Hi! How are you?", "Привет! Как дела?"),
    ("goodbye", "до свидания", "interjection", "Goodbye! See you tomorrow.", "До свидания! До завтра."),
    ("bye", "пока", "interjection", "Bye! Have a good day.", "Пока! Хорошего дня."),
    ("good morning", "доброе утро", "phrase", "Good morning! Did you sleep well?", "Доброе утро! Ты хорошо спал?"),
    ("good night", "спокойной ночи", "phrase", "Good night! Sleep well.", "Спокойной ночи! Спи хорошо."),
    ("please", "пожалуйста", "adverb", "Help me, please.", "Помоги мне, пожалуйста."),
    ("thank you", "спасибо", "phrase", "Thank you very much.", "Большое спасибо."),
    ("you're welcome", "пожалуйста (в ответ)", "phrase", "Thank you! You're welcome.", "Спасибо! Пожалуйста."),
    ("sorry", "извини(те)", "interjection", "Sorry, I am late.", "Извините, я опоздал."),
    ("excuse me", "извините", "phrase", "Excuse me, where is the bank?", "Извините, где банк?"),
    ("yes", "да", "adverb", "Yes, I understand.", "Да, я понимаю."),
    ("no", "нет", "adverb", "No, thank you.", "Нет, спасибо."),
    ("name", "имя", "noun", "What is your name?", "Как тебя зовут?"),
    ("nice to meet you", "приятно познакомиться", "phrase", "Nice to meet you!", "Приятно познакомиться!"),
    ("friend", "друг", "noun", "This is my friend.", "Это мой друг."),
    ("welcome", "добро пожаловать", "interjection", "Welcome to New York!", "Добро пожаловать в Нью-Йорк!"),
    ("how are you", "как дела", "phrase", "How are you today?", "Как у тебя дела сегодня?"),
    ("fine", "хорошо (о самочувствии)", "adjective", "I am fine, thank you.", "У меня всё хорошо, спасибо."),
    ("see you later", "увидимся позже", "phrase", "See you later!", "Увидимся позже!"),
]),
("personal_info", "Личная информация", ["g_001", "g_002"], [
    ("I", "я", "pronoun", "I am a student.", "Я студент."),
    ("you", "ты, вы", "pronoun", "You are my friend.", "Ты мой друг."),
    ("he", "он", "pronoun", "He is a doctor.", "Он врач."),
    ("she", "она", "pronoun", "She is a teacher.", "Она учитель."),
    ("it", "оно, это", "pronoun", "It is a small dog.", "Это маленькая собака."),
    ("we", "мы", "pronoun", "We are at home.", "Мы дома."),
    ("they", "они", "pronoun", "They are my parents.", "Они мои родители."),
    ("my", "мой", "pronoun", "This is my house.", "Это мой дом."),
    ("your", "твой, ваш", "pronoun", "What is your address?", "Какой у тебя адрес?"),
    ("his", "его", "pronoun", "His name is Tom.", "Его зовут Том."),
    ("her", "её", "pronoun", "Her name is Kate.", "Её зовут Кейт."),
    ("age", "возраст", "noun", "What is your age?", "Сколько тебе лет?"),
    ("years old", "лет (возраст)", "phrase", "I am thirty years old.", "Мне тридцать лет."),
    ("address", "адрес", "noun", "What is your address?", "Какой у вас адрес?"),
    ("phone number", "номер телефона", "noun", "What is your phone number?", "Какой у вас номер телефона?"),
    ("live", "жить", "verb", "I live in Miami.", "Я живу в Майами."),
    ("from", "из (страны, города)", "preposition", "I am from Russia.", "Я из России."),
    ("country", "страна", "noun", "What country are you from?", "Из какой ты страны?"),
    ("city", "город", "noun", "I live in a big city.", "Я живу в большом городе."),
    ("email", "электронная почта", "noun", "What is your email?", "Какая у тебя электронная почта?"),
]),
("numbers", "Числа", [], [
    ("zero", "ноль", "number", "The temperature is zero.", "Температура ноль градусов."),
    ("one", "один", "number", "I have one brother.", "У меня один брат."),
    ("two", "два", "number", "I have two sisters.", "У меня две сестры."),
    ("three", "три", "number", "There are three books.", "Здесь три книги."),
    ("four", "четыре", "number", "It is four o'clock.", "Сейчас четыре часа."),
    ("five", "пять", "number", "I need five dollars.", "Мне нужно пять долларов."),
    ("six", "шесть", "number", "We have six chairs.", "У нас шесть стульев."),
    ("seven", "семь", "number", "There are seven days in a week.", "В неделе семь дней."),
    ("eight", "восемь", "number", "The shop opens at eight.", "Магазин открывается в восемь."),
    ("nine", "девять", "number", "I go to bed at nine.", "Я ложусь спать в девять."),
    ("ten", "десять", "number", "I have ten fingers.", "У меня десять пальцев."),
    ("eleven", "одиннадцать", "number", "The bus comes at eleven.", "Автобус приходит в одиннадцать."),
    ("twelve", "двенадцать", "number", "There are twelve months.", "В году двенадцать месяцев."),
    ("thirteen", "тринадцать", "number", "She is thirteen years old.", "Ей тринадцать лет."),
    ("fourteen", "четырнадцать", "number", "I have fourteen dollars.", "У меня четырнадцать долларов."),
    ("fifteen", "пятнадцать", "number", "It takes fifteen minutes.", "Это занимает пятнадцать минут."),
    ("sixteen", "шестнадцать", "number", "He is sixteen years old.", "Ему шестнадцать лет."),
    ("seventeen", "семнадцать", "number", "There are seventeen students.", "Здесь семнадцать студентов."),
    ("eighteen", "восемнадцать", "number", "You can drive at eighteen.", "Можно водить машину с восемнадцати лет."),
    ("nineteen", "девятнадцать", "number", "I have nineteen dollars.", "У меня девятнадцать долларов."),
    ("twenty", "двадцать", "number", "There are twenty people here.", "Здесь двадцать человек."),
    ("thirty", "тридцать", "number", "I am thirty years old.", "Мне тридцать лет."),
    ("forty", "сорок", "number", "It costs forty dollars.", "Это стоит сорок долларов."),
    ("fifty", "пятьдесят", "number", "There are fifty states.", "Здесь пятьдесят штатов."),
    ("sixty", "шестьдесят", "number", "The trip takes sixty minutes.", "Поездка занимает шестьдесят минут."),
    ("seventy", "семьдесят", "number", "My grandfather is seventy.", "Моему дедушке семьдесят лет."),
    ("eighty", "восемьдесят", "number", "It costs eighty dollars.", "Это стоит восемьдесят долларов."),
    ("ninety", "девяносто", "number", "The room number is ninety.", "Номер комнаты — девяносто."),
    ("hundred", "сто", "number", "I have one hundred dollars.", "У меня сто долларов."),
    ("first", "первый", "adjective", "This is my first day.", "Это мой первый день."),
    ("second", "второй", "adjective", "Take the second street.", "Сверни на вторую улицу."),
    ("third", "третий", "adjective", "It is on the third floor.", "Это на третьем этаже."),
    ("how many", "сколько", "phrase", "How many books do you have?", "Сколько у тебя книг?"),
    ("number", "число, номер", "noun", "What is your room number?", "Какой у тебя номер комнаты?"),
]),
("colors", "Цвета", [], [
    ("red", "красный", "adjective", "The apple is red.", "Яблоко красное."),
    ("orange", "оранжевый", "adjective", "I like the orange car.", "Мне нравится оранжевая машина."),
    ("yellow", "жёлтый", "adjective", "The sun is yellow.", "Солнце жёлтое."),
    ("green", "зелёный", "adjective", "The grass is green.", "Трава зелёная."),
    ("blue", "синий", "adjective", "The sky is blue.", "Небо синее."),
    ("purple", "фиолетовый", "adjective", "She likes purple flowers.", "Ей нравятся фиолетовые цветы."),
    ("pink", "розовый", "adjective", "The dress is pink.", "Платье розовое."),
    ("black", "чёрный", "adjective", "He has a black car.", "У него чёрная машина."),
    ("white", "белый", "adjective", "Snow is white.", "Снег белый."),
    ("gray", "серый", "adjective", "The sky is gray today.", "Небо сегодня серое."),
    ("brown", "коричневый, карий", "adjective", "I have brown eyes.", "У меня карие глаза."),
    ("color", "цвет", "noun", "What color is your car?", "Какого цвета твоя машина?"),
]),
("days_months_time", "Дни, месяцы и время", ["g_009"], [
    ("Monday", "понедельник", "noun", "I work on Monday.", "Я работаю в понедельник."),
    ("Tuesday", "вторник", "noun", "We have a meeting on Tuesday.", "У нас встреча во вторник."),
    ("Wednesday", "среда", "noun", "The class is on Wednesday.", "Занятие в среду."),
    ("Thursday", "четверг", "noun", "I am busy on Thursday.", "Я занят в четверг."),
    ("Friday", "пятница", "noun", "See you on Friday!", "Увидимся в пятницу!"),
    ("Saturday", "суббота", "noun", "We rest on Saturday.", "Мы отдыхаем в субботу."),
    ("Sunday", "воскресенье", "noun", "The shop is closed on Sunday.", "Магазин закрыт по воскресеньям."),
    ("January", "январь", "noun", "My birthday is in January.", "Мой день рождения в январе."),
    ("February", "февраль", "noun", "It is cold in February.", "В феврале холодно."),
    ("March", "март", "noun", "Spring starts in March.", "Весна начинается в марте."),
    ("April", "апрель", "noun", "It often rains in April.", "В апреле часто идёт дождь."),
    ("May", "май", "noun", "The flowers bloom in May.", "Цветы цветут в мае."),
    ("June", "июнь", "noun", "School ends in June.", "Учебный год заканчивается в июне."),
    ("July", "июль", "noun", "It is hot in July.", "В июле жарко."),
    ("August", "август", "noun", "We go on vacation in August.", "Мы едем в отпуск в августе."),
    ("September", "сентябрь", "noun", "School starts in September.", "Учёба начинается в сентябре."),
    ("October", "октябрь", "noun", "The leaves fall in October.", "Листья падают в октябре."),
    ("November", "ноябрь", "noun", "Thanksgiving is in November.", "День благодарения в ноябре."),
    ("December", "декабрь", "noun", "Christmas is in December.", "Рождество в декабре."),
    ("today", "сегодня", "adverb", "What day is it today?", "Какой сегодня день?"),
    ("tomorrow", "завтра", "adverb", "See you tomorrow.", "Увидимся завтра."),
    ("yesterday", "вчера", "adverb", "I was busy yesterday.", "Вчера я был занят."),
    ("week", "неделя", "noun", "I work five days a week.", "Я работаю пять дней в неделю."),
    ("month", "месяц", "noun", "I pay rent every month.", "Я плачу за аренду каждый месяц."),
    ("year", "год", "noun", "I moved here last year.", "Я переехал сюда в прошлом году."),
    ("day", "день", "noun", "Have a nice day!", "Хорошего дня!"),
    ("hour", "час (продолжительность)", "noun", "The meeting is one hour.", "Встреча длится один час."),
    ("minute", "минута", "noun", "Wait one minute, please.", "Подождите одну минуту, пожалуйста."),
    ("o'clock", "час(ы) (время)", "noun", "It is three o'clock.", "Сейчас три часа."),
]),
("family", "Семья", ["g_002"], [
    ("mother", "мама", "noun", "This is my mother.", "Это моя мама."),
    ("father", "папа", "noun", "My father works in a bank.", "Мой папа работает в банке."),
    ("parents", "родители", "noun", "I live with my parents.", "Я живу с родителями."),
    ("sister", "сестра", "noun", "I have one sister.", "У меня есть сестра."),
    ("brother", "брат", "noun", "My brother is a student.", "Мой брат — студент."),
    ("son", "сын", "noun", "He has a son.", "У него есть сын."),
    ("daughter", "дочь", "noun", "She has a daughter.", "У неё есть дочь."),
    ("child", "ребёнок", "noun", "The child is happy.", "Ребёнок счастлив."),
    ("children", "дети", "noun", "We have two children.", "У нас двое детей."),
    ("baby", "младенец", "noun", "The baby is sleeping.", "Младенец спит."),
    ("husband", "муж", "noun", "My husband works late.", "Мой муж работает допоздна."),
    ("wife", "жена", "noun", "His wife is a nurse.", "Его жена — медсестра."),
    ("grandmother", "бабушка", "noun", "My grandmother cooks well.", "Моя бабушка хорошо готовит."),
    ("grandfather", "дедушка", "noun", "My grandfather is seventy.", "Моему дедушке семьдесят лет."),
    ("aunt", "тётя", "noun", "My aunt lives in Texas.", "Моя тётя живёт в Техасе."),
    ("uncle", "дядя", "noun", "My uncle has a car.", "У моего дяди есть машина."),
    ("cousin", "двоюродный брат/сестра", "noun", "My cousin is my friend.", "Мой двоюродный брат — мой друг."),
    ("family", "семья", "noun", "I love my family.", "Я люблю свою семью."),
    ("relative", "родственник", "noun", "She is my relative.", "Она моя родственница."),
    ("married", "женат, замужем", "adjective", "I am married.", "Я женат."),
]),
("food_drink", "Еда и напитки", ["g_004"], [
    ("bread", "хлеб", "noun", "I eat bread every morning.", "Я ем хлеб каждое утро."),
    ("butter", "сливочное масло", "noun", "Put butter on the bread.", "Намажь хлеб маслом."),
    ("milk", "молоко", "noun", "I drink milk every day.", "Я пью молоко каждый день."),
    ("water", "вода", "noun", "Can I have some water?", "Можно мне воды?"),
    ("juice", "сок", "noun", "I like orange juice.", "Мне нравится апельсиновый сок."),
    ("coffee", "кофе", "noun", "I drink coffee in the morning.", "Я пью кофе утром."),
    ("tea", "чай", "noun", "Would you like some tea?", "Хотите чаю?"),
    ("sugar", "сахар", "noun", "I don't take sugar.", "Я не кладу сахар."),
    ("salt", "соль", "noun", "Pass the salt, please.", "Передайте соль, пожалуйста."),
    ("egg", "яйцо", "noun", "I eat an egg for breakfast.", "Я ем яйцо на завтрак."),
    ("cheese", "сыр", "noun", "I like cheese sandwiches.", "Мне нравятся бутерброды с сыром."),
    ("meat", "мясо", "noun", "He doesn't eat meat.", "Он не ест мясо."),
    ("chicken", "курица", "noun", "We have chicken for dinner.", "У нас курица на ужин."),
    ("fish", "рыба", "noun", "I eat fish on Fridays.", "Я ем рыбу по пятницам."),
    ("rice", "рис", "noun", "Rice is cheap and healthy.", "Рис дешёвый и полезный."),
    ("soup", "суп", "noun", "The soup is hot.", "Суп горячий."),
    ("salad", "салат", "noun", "I want a salad, please.", "Я хочу салат, пожалуйста."),
    ("apple", "яблоко", "noun", "An apple a day is healthy.", "Яблоко в день полезно."),
    ("banana", "банан", "noun", "The banana is yellow.", "Банан жёлтый."),
    ("pizza", "пицца", "noun", "Let's order pizza tonight.", "Давай закажем пиццу сегодня вечером."),
    ("sandwich", "бутерброд", "noun", "I want a sandwich for lunch.", "Я хочу бутерброд на обед."),
    ("breakfast", "завтрак", "noun", "I have breakfast at seven.", "Я завтракаю в семь."),
    ("lunch", "обед", "noun", "We have lunch at noon.", "Мы обедаем в полдень."),
    ("dinner", "ужин", "noun", "Dinner is ready.", "Ужин готов."),
    ("restaurant", "ресторан", "noun", "Let's go to a restaurant.", "Давай сходим в ресторан."),
    ("menu", "меню", "noun", "Can I see the menu?", "Можно посмотреть меню?"),
    ("food", "еда", "noun", "This food is delicious.", "Эта еда вкусная."),
    ("hungry", "голодный", "adjective", "I am hungry.", "Я голоден."),
    ("thirsty", "хочется пить", "adjective", "I am thirsty.", "Мне хочется пить."),
    ("cook", "готовить (еду)", "verb", "I cook dinner every day.", "Я готовлю ужин каждый день."),
    ("eat", "есть, кушать", "verb", "I eat lunch at noon.", "Я обедаю в полдень."),
    ("drink", "пить", "verb", "I drink water every day.", "Я пью воду каждый день."),
    ("sweet", "сладкий", "adjective", "This cake is very sweet.", "Этот торт очень сладкий."),
    ("delicious", "вкусный", "adjective", "The soup is delicious.", "Суп очень вкусный."),
    ("vegetable", "овощ", "noun", "I eat vegetables every day.", "Я ем овощи каждый день."),
    ("potato", "картофель", "noun", "I like baked potato.", "Мне нравится печёная картошка."),
    ("tomato", "помидор", "noun", "The tomato is red.", "Помидор красный."),
    ("onion", "лук", "noun", "Cut the onion, please.", "Нарежь лук, пожалуйста."),
    ("fruit", "фрукт", "noun", "Fruit is good for you.", "Фрукты полезны для тебя."),
    ("cup", "чашка", "noun", "A cup of coffee, please.", "Чашку кофе, пожалуйста."),
    ("plate", "тарелка", "noun", "Put the food on the plate.", "Положи еду на тарелку."),
    ("spoon", "ложка", "noun", "I need a spoon.", "Мне нужна ложка."),
    ("fork", "вилка", "noun", "Can I have a fork?", "Можно мне вилку?"),
    ("knife", "нож", "noun", "The knife is sharp.", "Нож острый."),
    ("glass", "стакан", "noun", "A glass of water, please.", "Стакан воды, пожалуйста."),
]),
("home_objects", "Дом и предметы дома", ["g_006", "g_008"], [
    ("house", "дом", "noun", "This is my house.", "Это мой дом."),
    ("apartment", "квартира", "noun", "I live in an apartment.", "Я живу в квартире."),
    ("room", "комната", "noun", "This room is big.", "Эта комната большая."),
    ("kitchen", "кухня", "noun", "The kitchen is small.", "Кухня маленькая."),
    ("bathroom", "ванная", "noun", "The bathroom is upstairs.", "Ванная наверху."),
    ("bedroom", "спальня", "noun", "My bedroom has a big bed.", "В моей спальне большая кровать."),
    ("living room", "гостиная", "noun", "We watch TV in the living room.", "Мы смотрим телевизор в гостиной."),
    ("door", "дверь", "noun", "Please close the door.", "Пожалуйста, закрой дверь."),
    ("window", "окно", "noun", "Open the window, please.", "Открой окно, пожалуйста."),
    ("table", "стол", "noun", "The book is on the table.", "Книга на столе."),
    ("chair", "стул", "noun", "Please sit on the chair.", "Пожалуйста, сядь на стул."),
    ("bed", "кровать", "noun", "I sleep in my bed.", "Я сплю в своей кровати."),
    ("sofa", "диван", "noun", "We sit on the sofa.", "Мы сидим на диване."),
    ("TV", "телевизор", "noun", "We watch TV in the evening.", "Мы смотрим телевизор вечером."),
    ("lamp", "лампа", "noun", "Turn on the lamp.", "Включи лампу."),
    ("phone", "телефон", "noun", "My phone is new.", "Мой телефон новый."),
    ("computer", "компьютер", "noun", "I work on my computer.", "Я работаю за компьютером."),
    ("key", "ключ", "noun", "I lost my key.", "Я потерял ключ."),
    ("wall", "стена", "noun", "There is a picture on the wall.", "На стене висит картина."),
    ("floor", "пол, этаж", "noun", "The floor is clean.", "Пол чистый."),
    ("roof", "крыша", "noun", "The roof is new.", "Крыша новая."),
    ("garden", "сад", "noun", "We have a small garden.", "У нас маленький сад."),
    ("garage", "гараж", "noun", "The car is in the garage.", "Машина в гараже."),
    ("mirror", "зеркало", "noun", "Look in the mirror.", "Посмотри в зеркало."),
    ("clock", "часы (настенные)", "noun", "The clock is on the wall.", "Часы висят на стене."),
    ("closet", "шкаф", "noun", "Put your clothes in the closet.", "Положи одежду в шкаф."),
    ("shower", "душ", "noun", "I take a shower every morning.", "Я принимаю душ каждое утро."),
    ("sink", "раковина", "noun", "Wash your hands in the sink.", "Помой руки в раковине."),
    ("towel", "полотенце", "noun", "Give me a towel, please.", "Дай мне полотенце, пожалуйста."),
    ("blanket", "одеяло", "noun", "The blanket is warm.", "Одеяло тёплое."),
    ("pillow", "подушка", "noun", "My pillow is soft.", "Моя подушка мягкая."),
    ("furniture", "мебель", "noun", "We need new furniture.", "Нам нужна новая мебель."),
    ("refrigerator", "холодильник", "noun", "The milk is in the refrigerator.", "Молоко в холодильнике."),
    ("stove", "плита", "noun", "The stove is hot.", "Плита горячая."),
]),
("clothes", "Одежда", [], [
    ("shirt", "рубашка", "noun", "He is wearing a blue shirt.", "На нём синяя рубашка."),
    ("T-shirt", "футболка", "noun", "I bought a new T-shirt.", "Я купил новую футболку."),
    ("pants", "брюки", "noun", "These pants are too long.", "Эти брюки слишком длинные."),
    ("jeans", "джинсы", "noun", "I like these jeans.", "Мне нравятся эти джинсы."),
    ("dress", "платье", "noun", "She is wearing a red dress.", "На ней красное платье."),
    ("skirt", "юбка", "noun", "The skirt is short.", "Юбка короткая."),
    ("shoes", "обувь, туфли", "noun", "I need new shoes.", "Мне нужна новая обувь."),
    ("socks", "носки", "noun", "My socks are wet.", "Мои носки мокрые."),
    ("jacket", "куртка", "noun", "Wear a jacket, it's cold.", "Надень куртку, холодно."),
    ("coat", "пальто", "noun", "Take your coat.", "Возьми пальто."),
    ("hat", "шапка, шляпа", "noun", "He is wearing a hat.", "На нём шапка."),
    ("gloves", "перчатки", "noun", "Put on your gloves.", "Надень перчатки."),
    ("scarf", "шарф", "noun", "She has a warm scarf.", "У неё тёплый шарф."),
    ("sweater", "свитер", "noun", "This sweater is warm.", "Этот свитер тёплый."),
    ("shorts", "шорты", "noun", "I wear shorts in summer.", "Летом я ношу шорты."),
    ("boots", "сапоги, ботинки", "noun", "I need warm boots.", "Мне нужны тёплые сапоги."),
    ("belt", "ремень", "noun", "The belt is black.", "Ремень чёрный."),
    ("clothes", "одежда", "noun", "I need to buy new clothes.", "Мне нужно купить новую одежду."),
]),
("body_health", "Тело и здоровье", [], [
    ("head", "голова", "noun", "My head hurts.", "У меня болит голова."),
    ("hair", "волосы", "noun", "She has long hair.", "У неё длинные волосы."),
    ("face", "лицо", "noun", "Wash your face.", "Умой лицо."),
    ("eye", "глаз", "noun", "He has blue eyes.", "У него голубые глаза."),
    ("ear", "ухо", "noun", "My ear hurts.", "У меня болит ухо."),
    ("nose", "нос", "noun", "My nose is cold.", "У меня холодный нос."),
    ("mouth", "рот", "noun", "Open your mouth, please.", "Откройте рот, пожалуйста."),
    ("tooth", "зуб", "noun", "My tooth hurts.", "У меня болит зуб."),
    ("hand", "рука (кисть)", "noun", "Wash your hands.", "Помой руки."),
    ("arm", "рука (от плеча)", "noun", "My arm hurts.", "У меня болит рука."),
    ("leg", "нога", "noun", "My leg hurts.", "У меня болит нога."),
    ("foot", "стопa", "noun", "My foot hurts.", "У меня болит стопа."),
    ("back", "спина", "noun", "My back hurts.", "У меня болит спина."),
    ("stomach", "живот", "noun", "My stomach hurts.", "У меня болит живот."),
    ("heart", "сердце", "noun", "My heart beats fast.", "Моё сердце бьётся быстро."),
    ("body", "тело", "noun", "Drink water for your body.", "Пей воду для своего тела."),
    ("sick", "больной", "adjective", "I am sick today.", "Сегодня я болею."),
    ("healthy", "здоровый", "adjective", "Eat healthy food.", "Ешь здоровую еду."),
    ("pain", "боль", "noun", "I have pain in my back.", "У меня боль в спине."),
    ("headache", "головная боль", "noun", "I have a headache.", "У меня болит голова."),
    ("fever", "температура, жар", "noun", "The child has a fever.", "У ребёнка температура."),
    ("doctor", "врач", "noun", "I need to see a doctor.", "Мне нужно к врачу."),
    ("hospital", "больница", "noun", "He is in the hospital.", "Он в больнице."),
    ("medicine", "лекарство", "noun", "Take this medicine twice a day.", "Принимай это лекарство дважды в день."),
]),
("actions_verbs", "Частотные глаголы", ["g_003", "g_005", "g_007"], [
    ("be", "быть", "verb", "I want to be a doctor.", "Я хочу быть врачом."),
    ("have", "иметь", "verb", "I have a car.", "У меня есть машина."),
    ("go", "идти, ехать", "verb", "I go to work every day.", "Я хожу на работу каждый день."),
    ("want", "хотеть", "verb", "I want a coffee.", "Я хочу кофе."),
    ("like", "нравиться", "verb", "I like this song.", "Мне нравится эта песня."),
    ("can", "мочь, уметь", "verb", "I can swim.", "Я умею плавать."),
    ("need", "нуждаться", "verb", "I need help.", "Мне нужна помощь."),
    ("do", "делать (вспом./полнозн.)", "verb", "What do you do?", "Чем ты занимаешься?"),
    ("make", "делать, готовить", "verb", "I make dinner every day.", "Я готовлю ужин каждый день."),
    ("take", "брать", "verb", "Take my hand.", "Возьми меня за руку."),
    ("get", "получать, добираться", "verb", "I get up at seven.", "Я встаю в семь."),
    ("give", "давать", "verb", "Give me your phone number.", "Дай мне свой номер телефона."),
    ("see", "видеть", "verb", "I see a bird.", "Я вижу птицу."),
    ("look", "смотреть", "verb", "Look at this picture.", "Посмотри на эту картинку."),
    ("know", "знать", "verb", "I know the answer.", "Я знаю ответ."),
    ("think", "думать", "verb", "I think you are right.", "Я думаю, ты прав."),
    ("say", "говорить, сказать", "verb", "What did you say?", "Что ты сказал?"),
    ("tell", "рассказать, сказать", "verb", "Tell me your name.", "Скажи мне своё имя."),
    ("ask", "спрашивать, просить", "verb", "Can I ask a question?", "Можно задать вопрос?"),
    ("answer", "отвечать", "verb", "Please answer the question.", "Пожалуйста, ответь на вопрос."),
    ("come", "приходить", "verb", "Come here, please.", "Подойди сюда, пожалуйста."),
    ("leave", "уходить, уезжать", "verb", "I leave home at eight.", "Я выхожу из дома в восемь."),
    ("work", "работать", "verb", "I work in an office.", "Я работаю в офисе."),
    ("study", "учиться, изучать", "verb", "I study English.", "Я изучаю английский."),
    ("learn", "учить, узнавать", "verb", "I want to learn English.", "Я хочу выучить английский."),
    ("read", "читать", "verb", "I read every night.", "Я читаю каждый вечер."),
    ("write", "писать", "verb", "Write your name here.", "Напиши здесь своё имя."),
    ("speak", "говорить (на языке)", "verb", "Do you speak English?", "Ты говоришь по-английски?"),
    ("listen", "слушать", "verb", "Listen to me, please.", "Послушай меня, пожалуйста."),
    ("understand", "понимать", "verb", "I understand you.", "Я тебя понимаю."),
    ("help", "помогать", "verb", "Can you help me?", "Ты можешь мне помочь?"),
    ("stay", "оставаться", "verb", "Stay here, please.", "Останься здесь, пожалуйста."),
    ("sleep", "спать", "verb", "I sleep eight hours.", "Я сплю восемь часов."),
    ("wash", "мыть, стирать", "verb", "I wash my hands.", "Я мою руки."),
    ("clean up", "убирать, наводить порядок", "verb", "I clean up my room on Sunday.", "Я убираю в комнате по воскресеньям."),
    ("buy", "покупать", "verb", "I want to buy a car.", "Я хочу купить машину."),
    ("sell", "продавать", "verb", "They sell fresh fruit.", "Они продают свежие фрукты."),
    ("pay", "платить", "verb", "I pay with a credit card.", "Я плачу кредитной картой."),
    ("cost", "стоить", "verb", "How much does it cost?", "Сколько это стоит?"),
    ("open", "открывать", "verb", "Open the door, please.", "Открой дверь, пожалуйста."),
    ("close", "закрывать", "verb", "Close the window, please.", "Закрой окно, пожалуйста."),
    ("start", "начинать", "verb", "The class starts at nine.", "Занятие начинается в девять."),
    ("finish", "заканчивать", "verb", "I finish work at five.", "Я заканчиваю работу в пять."),
    ("play", "играть", "verb", "Children play in the park.", "Дети играют в парке."),
    ("watch", "смотреть (за чем-то)", "verb", "I watch movies on weekends.", "Я смотрю фильмы по выходным."),
    ("meet", "встречать(ся)", "verb", "Let's meet at six.", "Давай встретимся в шесть."),
    ("call", "звонить", "verb", "Call me tonight.", "Позвони мне сегодня вечером."),
    ("wait", "ждать", "verb", "Wait for me, please.", "Подожди меня, пожалуйста."),
    ("walk", "идти пешком, гулять", "verb", "I walk to work.", "Я хожу на работу пешком."),
    ("run", "бежать", "verb", "I run every morning.", "Я бегаю каждое утро."),
    ("drive", "водить машину", "verb", "I drive to work.", "Я езжу на работу на машине."),
    ("sit", "сидеть", "verb", "Please sit down.", "Пожалуйста, садитесь."),
    ("stand", "стоять", "verb", "Please stand up.", "Пожалуйста, встаньте."),
]),
("adjectives_basic", "Прилагательные", [], [
    ("big", "большой", "adjective", "The house is big.", "Дом большой."),
    ("small", "маленький", "adjective", "The room is small.", "Комната маленькая."),
    ("hot", "горячий, жаркий", "adjective", "The soup is hot.", "Суп горячий."),
    ("cold", "холодный", "adjective", "The water is cold.", "Вода холодная."),
    ("good", "хороший", "adjective", "This is a good idea.", "Это хорошая идея."),
    ("bad", "плохой", "adjective", "The weather is bad today.", "Сегодня плохая погода."),
    ("new", "новый", "adjective", "I have a new phone.", "У меня новый телефон."),
    ("old", "старый", "adjective", "This is an old house.", "Это старый дом."),
    ("happy", "счастливый", "adjective", "She is very happy.", "Она очень счастлива."),
    ("sad", "грустный", "adjective", "He looks sad today.", "Он сегодня выглядит грустным."),
    ("easy", "лёгкий, простой", "adjective", "This exercise is easy.", "Это упражнение лёгкое."),
    ("difficult", "трудный", "adjective", "English grammar is difficult.", "Английская грамматика трудная."),
    ("fast", "быстрый", "adjective", "This car is fast.", "Эта машина быстрая."),
    ("slow", "медленный", "adjective", "The internet is slow.", "Интернет медленный."),
    ("tall", "высокий (о человеке)", "adjective", "My brother is tall.", "Мой брат высокий."),
    ("short", "низкий, короткий", "adjective", "The line is short.", "Очередь короткая."),
    ("young", "молодой", "adjective", "She is very young.", "Она очень молодая."),
    ("beautiful", "красивый", "adjective", "The city is beautiful.", "Город красивый."),
    ("clean", "чистый", "adjective", "The kitchen is clean.", "Кухня чистая."),
    ("dirty", "грязный", "adjective", "My shoes are dirty.", "Мои туфли грязные."),
    ("expensive", "дорогой", "adjective", "This car is expensive.", "Эта машина дорогая."),
    ("cheap", "дешёвый", "adjective", "The tickets are cheap.", "Билеты дешёвые."),
    ("strong", "сильный", "adjective", "He is very strong.", "Он очень сильный."),
    ("weak", "слабый", "adjective", "I feel weak today.", "Сегодня я чувствую слабость."),
    ("full", "полный", "adjective", "The bus is full.", "Автобус полный."),
    ("empty", "пустой", "adjective", "The box is empty.", "Коробка пустая."),
    ("near", "близкий, рядом", "adjective", "The store is near my house.", "Магазин рядом с моим домом."),
    ("far", "далёкий, далеко", "adjective", "The airport is far from here.", "Аэропорт далеко отсюда."),
    ("early", "ранний, рано", "adjective", "I wake up early.", "Я просыпаюсь рано."),
    ("late", "поздний, поздно", "adjective", "I am late for work.", "Я опаздываю на работу."),
    ("important", "важный", "adjective", "This document is important.", "Этот документ важный."),
    ("tired", "уставший", "adjective", "I am tired today.", "Сегодня я устал."),
    ("busy", "занятой", "adjective", "She is busy this week.", "На этой неделе она занята."),
    ("free", "свободный", "adjective", "Are you free tomorrow?", "Ты свободен завтра?"),
    ("different", "другой, разный", "adjective", "We have different opinions.", "У нас разные мнения."),
    ("same", "такой же, одинаковый", "adjective", "We have the same phone.", "У нас одинаковые телефоны."),
]),
("shopping", "Магазин", ["g_004"], [
    ("shop", "магазин", "noun", "This shop sells shoes.", "Этот магазин продаёт обувь."),
    ("store", "магазин", "noun", "The store is open until nine.", "Магазин открыт до девяти."),
    ("supermarket", "супермаркет", "noun", "I buy food at the supermarket.", "Я покупаю еду в супермаркете."),
    ("market", "рынок", "noun", "We buy vegetables at the market.", "Мы покупаем овощи на рынке."),
    ("money", "деньги", "noun", "I don't have much money.", "У меня немного денег."),
    ("price", "цена", "noun", "What is the price of this shirt?", "Какая цена у этой рубашки?"),
    ("cash", "наличные", "noun", "Do you accept cash?", "Вы принимаете наличные?"),
    ("credit card", "кредитная карта", "noun", "I pay with a credit card.", "Я плачу кредитной картой."),
    ("receipt", "чек", "noun", "Can I have the receipt, please?", "Можно чек, пожалуйста?"),
    ("bag", "сумка, пакет", "noun", "Put it in the bag, please.", "Положите это в пакет, пожалуйста."),
    ("size", "размер", "noun", "What size do you need?", "Какой размер вам нужен?"),
    ("discount", "скидка", "noun", "There is a discount today.", "Сегодня действует скидка."),
    ("sale", "распродажа", "noun", "There is a big sale today.", "Сегодня большая распродажа."),
    ("cashier", "кассир", "noun", "The cashier is very friendly.", "Кассир очень дружелюбный."),
    ("customer", "покупатель, клиент", "noun", "The customer is always right.", "Клиент всегда прав."),
    ("change", "сдача", "noun", "Here is your change.", "Вот ваша сдача."),
    ("wallet", "кошелёк", "noun", "I lost my wallet.", "Я потерял свой кошелёк."),
    ("gift", "подарок", "noun", "This is a gift for you.", "Это подарок для тебя."),
    ("shopping list", "список покупок", "noun", "I wrote a shopping list.", "Я написал список покупок."),
    ("free of charge", "бесплатный", "adjective", "This service is free.", "Эта услуга бесплатная."),
]),
("directions_transport", "Направления и транспорт", ["g_008"], [
    ("left", "налево, левый", "adverb", "Turn left at the corner.", "Поверни налево на углу."),
    ("right", "направо, правый", "adverb", "Turn right here.", "Поверни здесь направо."),
    ("straight", "прямо", "adverb", "Go straight ahead.", "Иди прямо."),
    ("street", "улица", "noun", "I live on Main Street.", "Я живу на Мейн-стрит."),
    ("road", "дорога", "noun", "The road is busy today.", "Дорога сегодня загружена."),
    ("corner", "угол, перекрёсток", "noun", "The store is on the corner.", "Магазин на углу."),
    ("map", "карта", "noun", "Can you show me on the map?", "Можешь показать мне на карте?"),
    ("bus", "автобус", "noun", "I take the bus to work.", "Я езжу на работу на автобусе."),
    ("train", "поезд", "noun", "The train is late.", "Поезд опаздывает."),
    ("car", "машина", "noun", "I have a new car.", "У меня новая машина."),
    ("taxi", "такси", "noun", "Let's take a taxi.", "Давай возьмём такси."),
    ("bike", "велосипед", "noun", "I ride my bike to school.", "Я езжу в школу на велосипеде."),
    ("airplane", "самолёт", "noun", "The airplane is flying high.", "Самолёт летит высоко."),
    ("station", "станция, вокзал", "noun", "Where is the train station?", "Где находится вокзал?"),
    ("airport", "аэропорт", "noun", "The airport is far from here.", "Аэропорт далеко отсюда."),
    ("ticket", "билет", "noun", "I need one ticket, please.", "Мне нужен один билет, пожалуйста."),
    ("stop", "остановка", "noun", "The bus stop is near here.", "Автобусная остановка рядом."),
    ("turn", "поворачивать", "verb", "Turn left at the light.", "Поверни налево у светофора."),
    ("cross", "переходить (улицу)", "verb", "Cross the street carefully.", "Переходи улицу осторожно."),
    ("traffic light", "светофор", "noun", "Stop at the traffic light.", "Остановись у светофора."),
    ("direction", "направление", "noun", "I don't know the direction.", "Я не знаю направление."),
    ("subway", "метро", "noun", "I take the subway every day.", "Я езжу на метро каждый день."),
    ("parking", "парковка", "noun", "The parking is full.", "Парковка заполнена."),
    ("gas station", "заправка", "noun", "We need to stop at a gas station.", "Нам нужно остановиться на заправке."),
]),
("pharmacy_doctor", "Аптека и врач", [], [
    ("pharmacy", "аптека", "noun", "I need to go to the pharmacy.", "Мне нужно в аптеку."),
    ("pill", "таблетка", "noun", "Take one pill twice a day.", "Принимай одну таблетку дважды в день."),
    ("prescription", "рецепт на лекарство", "noun", "I need a prescription for this medicine.", "Мне нужен рецепт на это лекарство."),
    ("appointment", "приём, запись", "noun", "I have a doctor's appointment.", "У меня приём у врача."),
    ("nurse", "медсестра, медбрат", "noun", "The nurse is very kind.", "Медсестра очень добрая."),
    ("patient", "пациент", "noun", "The patient feels better.", "Пациент чувствует себя лучше."),
    ("symptom", "симптом", "noun", "What are your symptoms?", "Какие у вас симптомы?"),
    ("temperature", "температура тела", "noun", "My temperature is high.", "У меня высокая температура."),
    ("insurance", "страховка", "noun", "Do you have health insurance?", "У вас есть медицинская страховка?"),
    ("emergency", "экстренный случай", "noun", "This is an emergency!", "Это экстренный случай!"),
    ("ambulance", "скорая помощь", "noun", "Call an ambulance!", "Вызовите скорую!"),
    ("clinic", "клиника", "noun", "The clinic is open now.", "Клиника сейчас открыта."),
    ("checkup", "медосмотр", "noun", "I need a checkup.", "Мне нужен медосмотр."),
    ("allergy", "аллергия", "noun", "I have an allergy to nuts.", "У меня аллергия на орехи."),
    ("injury", "травма", "noun", "He has a leg injury.", "У него травма ноги."),
    ("bandage", "бинт, повязка", "noun", "Put a bandage on the cut.", "Наложи бинт на порез."),
    ("dentist", "стоматолог", "noun", "I have a dentist appointment.", "У меня запись к стоматологу."),
    ("X-ray", "рентген", "noun", "The doctor did an X-ray.", "Врач сделал рентген."),
    ("cough", "кашель", "noun", "I have a bad cough.", "У меня сильный кашель."),
    ("flu", "грипп", "noun", "I have the flu.", "У меня грипп."),
]),
("documents_bank", "Документы и банк", [], [
    ("document", "документ", "noun", "I need this document.", "Мне нужен этот документ."),
    ("passport", "паспорт", "noun", "I have my passport with me.", "У меня с собой паспорт."),
    ("driver's license", "водительские права", "noun", "I need my driver's license.", "Мне нужны водительские права."),
    ("ID card", "удостоверение личности", "noun", "Please show your ID card.", "Пожалуйста, покажите удостоверение личности."),
    ("social security number", "номер соц. страхования", "noun", "What is your social security number?", "Какой у вас номер социального страхования?"),
    ("form", "бланк, форма", "noun", "Please fill out this form.", "Пожалуйста, заполните этот бланк."),
    ("signature", "подпись", "noun", "I need your signature here.", "Мне нужна ваша подпись здесь."),
    ("bank", "банк", "noun", "I need to go to the bank.", "Мне нужно в банк."),
    ("account", "счёт (банковский)", "noun", "I opened a bank account.", "Я открыл банковский счёт."),
    ("deposit", "вносить (деньги)", "verb", "I want to deposit money.", "Я хочу внести деньги."),
    ("withdraw", "снимать (деньги)", "verb", "I want to withdraw cash.", "Я хочу снять наличные."),
    ("application", "заявление, анкета", "noun", "I filled out the application.", "Я заполнил анкету."),
    ("date of birth", "дата рождения", "noun", "What is your date of birth?", "Какая у вас дата рождения?"),
    ("government", "правительство, госорган", "noun", "This is a government office.", "Это государственное учреждение."),
    ("office", "офис, учреждение", "noun", "The office is closed today.", "Офис сегодня закрыт."),
    ("department", "отдел, ведомство", "noun", "Go to the next department.", "Идите в следующий отдел."),
    ("fee", "сбор, плата", "noun", "There is a small fee.", "Есть небольшая плата."),
    ("line", "очередь", "noun", "The line is very long.", "Очередь очень длинная."),
    ("wait in line", "стоять в очереди", "phrase", "We have to wait in line.", "Нам нужно постоять в очереди."),
    ("renew", "продлить (документ)", "verb", "I need to renew my license.", "Мне нужно продлить права."),
]),
("work_basic", "Работа", ["g_003"], [
    ("job", "работа (место)", "noun", "I have a new job.", "У меня новая работа."),
    ("boss", "начальник", "noun", "My boss is very nice.", "Мой начальник очень приятный."),
    ("employee", "сотрудник", "noun", "She is a good employee.", "Она хороший сотрудник."),
    ("company", "компания", "noun", "I work for a big company.", "Я работаю в большой компании."),
    ("salary", "зарплата", "noun", "The salary is good.", "Зарплата хорошая."),
    ("schedule", "расписание, график", "noun", "What is your work schedule?", "Какой у тебя рабочий график?"),
    ("meeting", "встреча, совещание", "noun", "We have a meeting at ten.", "У нас встреча в десять."),
    ("coworker", "коллега", "noun", "My coworker helped me today.", "Мой коллега помог мне сегодня."),
    ("resume", "резюме", "noun", "I sent my resume.", "Я отправил своё резюме."),
    ("interview", "собеседование", "noun", "I have a job interview tomorrow.", "У меня завтра собеседование."),
    ("hire", "нанимать", "verb", "They hired a new manager.", "Они наняли нового менеджера."),
    ("break", "перерыв", "noun", "I take a break at noon.", "Я делаю перерыв в полдень."),
    ("shift", "смена (рабочая)", "noun", "I work the night shift.", "Я работаю в ночную смену."),
    ("full-time", "полная занятость", "adjective", "I have a full-time job.", "У меня работа на полную ставку."),
    ("part-time", "неполная занятость", "adjective", "She works part-time.", "Она работает неполный день."),
    ("manager", "менеджер, руководитель", "noun", "The manager is in a meeting.", "Менеджер на встрече."),
    ("task", "задача", "noun", "I have many tasks today.", "У меня сегодня много задач."),
    ("experience", "опыт работы", "noun", "I have five years of experience.", "У меня пять лет опыта."),
]),
("weather_seasons", "Погода и времена года", [], [
    ("weather", "погода", "noun", "The weather is nice today.", "Сегодня хорошая погода."),
    ("sun", "солнце", "noun", "The sun is shining.", "Солнце светит."),
    ("sunny", "солнечный", "adjective", "It is sunny today.", "Сегодня солнечно."),
    ("rain", "дождь", "noun", "I like the sound of rain.", "Мне нравится звук дождя."),
    ("rainy", "дождливый", "adjective", "It is rainy today.", "Сегодня дождливо."),
    ("snow", "снег", "noun", "The snow is white.", "Снег белый."),
    ("snowy", "снежный", "adjective", "It is snowy in winter.", "Зимой снежно."),
    ("wind", "ветер", "noun", "The wind is strong today.", "Сегодня сильный ветер."),
    ("windy", "ветреный", "adjective", "It is windy today.", "Сегодня ветрено."),
    ("cloud", "облако", "noun", "There is one cloud in the sky.", "На небе одно облако."),
    ("cloudy", "облачный", "adjective", "It is cloudy today.", "Сегодня облачно."),
    ("warm", "тёплый", "adjective", "The water is warm.", "Вода тёплая."),
    ("cool", "прохладный", "adjective", "The evening is cool.", "Вечер прохладный."),
    ("spring", "весна", "noun", "I like spring.", "Мне нравится весна."),
    ("summer", "лето", "noun", "Summer is hot.", "Лето жаркое."),
    ("autumn", "осень", "noun", "The leaves fall in autumn.", "Листья падают осенью."),
    ("winter", "зима", "noun", "Winter is cold.", "Зима холодная."),
    ("season", "время года", "noun", "What is your favorite season?", "Какое твоё любимое время года?"),
]),
("prepositions", "Предлоги места и времени", ["g_008", "g_009"], [
    ("in", "в (место/время)", "preposition", "The keys are in the bag.", "Ключи в сумке."),
    ("on", "на", "preposition", "The book is on the table.", "Книга на столе."),
    ("at", "у, в (точное место/время)", "preposition", "I am at home.", "Я дома."),
    ("under", "под", "preposition", "The cat is under the table.", "Кошка под столом."),
    ("over", "над", "preposition", "The lamp is over the table.", "Лампа над столом."),
    ("next to", "рядом с", "preposition", "The bank is next to the store.", "Банк рядом с магазином."),
    ("between", "между", "preposition", "The pharmacy is between the bank and the store.", "Аптека между банком и магазином."),
    ("behind", "позади, за", "preposition", "The garden is behind the house.", "Сад позади дома."),
    ("in front of", "перед", "preposition", "The car is in front of the house.", "Машина перед домом."),
    ("before", "до, перед (время)", "preposition", "I eat breakfast before work.", "Я завтракаю перед работой."),
    ("after", "после", "preposition", "I go home after work.", "Я иду домой после работы."),
    ("during", "во время", "preposition", "I was quiet during the meeting.", "Я молчал во время встречи."),
    ("from...to", "от...до", "preposition", "I work from nine to five.", "Я работаю с девяти до пяти."),
    ("with", "с (кем-то)", "preposition", "I live with my family.", "Я живу со своей семьёй."),
    ("without", "без", "preposition", "I can't live without coffee.", "Я не могу жить без кофе."),
    ("there is", "есть, имеется", "phrase", "There is a book on the table.", "На столе есть книга."),
    ("there are", "есть, имеются (мн.ч.)", "phrase", "There are three chairs in the room.", "В комнате есть три стула."),
    ("a lot of", "много", "phrase", "There is a lot of food.", "Здесь много еды."),
    ("some", "несколько, немного", "determiner", "I need some water.", "Мне нужно немного воды."),
    ("any", "какой-нибудь, никакой", "determiner", "I don't have any money.", "У меня нет денег."),
]),
("question_words", "Вопросительные слова", ["g_005"], [
    ("what", "что", "pronoun", "What is this?", "Что это?"),
    ("who", "кто", "pronoun", "Who is that?", "Кто это?"),
    ("where", "где", "adverb", "Where is the bathroom?", "Где ванная?"),
    ("when", "когда", "adverb", "When is the meeting?", "Когда встреча?"),
    ("why", "почему", "adverb", "Why are you late?", "Почему ты опоздал?"),
    ("how", "как", "adverb", "How do you say this in English?", "Как это сказать по-английски?"),
    ("which", "который, какой", "pronoun", "Which bus goes downtown?", "Какой автобус едет в центр?"),
    ("whose", "чей", "pronoun", "Whose phone is this?", "Чей это телефон?"),
]),
("everyday_words", "Повседневные слова", [], [
    ("always", "всегда", "adverb", "I always drink coffee in the morning.", "Я всегда пью кофе утром."),
    ("usually", "обычно", "adverb", "I usually walk to work.", "Я обычно хожу на работу пешком."),
    ("sometimes", "иногда", "adverb", "I sometimes cook dinner.", "Иногда я готовлю ужин."),
    ("never", "никогда", "adverb", "I never eat meat.", "Я никогда не ем мясо."),
    ("often", "часто", "adverb", "He often calls his mother.", "Он часто звонит маме."),
    ("also", "тоже, также", "adverb", "I also like tea.", "Мне тоже нравится чай."),
    ("very", "очень", "adverb", "This soup is very hot.", "Этот суп очень горячий."),
    ("too", "тоже", "adverb", "I want coffee too.", "Я тоже хочу кофе."),
    ("here", "здесь", "adverb", "Come here, please.", "Подойди сюда, пожалуйста."),
    ("there", "там", "adverb", "The keys are there.", "Ключи там."),
    ("now", "сейчас", "adverb", "I am busy now.", "Сейчас я занят."),
    ("then", "потом, тогда", "adverb", "First eat, then sleep.", "Сначала поешь, потом спи."),
    ("because", "потому что", "conjunction", "I am tired because I work a lot.", "Я устал, потому что много работаю."),
    ("but", "но", "conjunction", "I like tea but not coffee.", "Мне нравится чай, но не кофе."),
    ("and", "и", "conjunction", "I have a mother and a father.", "У меня есть мама и папа."),
    ("or", "или", "conjunction", "Tea or coffee?", "Чай или кофе?"),
]),
]

GRAMMAR = [
    ("g_001", "Глагол to be", [
        "Глагол «to be» (быть) — самый важный глагол в английском. В настоящем времени у него три формы: am, is, are. «I am» — я есть, «he/she/it is» — он/она/оно есть, «you/we/they are» — ты/мы/они есть. Отрицание образуется добавлением «not»: is not (isn't), are not (aren't). В вопросах глагол ставится перед подлежащим: «Are you tired?»"
    ], ["I am a student.", "She is happy.", "We are at home.", "They aren't ready.", "Are you from Russia?"], ["ex_001","ex_002","ex_003"]),
    ("g_002", "Личные и притяжательные местоимения", [
        "Личные местоимения (I, you, he, she, it, we, they) заменяют существительные и стоят перед глаголом. Притяжательные местоимения (my, your, his, her, its, our, their) показывают, кому что принадлежит, и ставятся перед существительным: «This is my book.»"
    ], ["I live in Miami.", "He is my brother.", "This is her phone.", "Our house is big."], ["ex_004","ex_005","ex_006"]),
    ("g_003", "Present Simple (простое настоящее время)", [
        "Present Simple используется для привычных действий и фактов. С I/you/we/they глагол остаётся в базовой форме: «I work». С he/she/it добавляется окончание -s: «He works». Слова-маркеры: usually, often, always, every day."
    ], ["I work every day.", "She works in a bank.", "They live in New York.", "He drinks coffee every morning."], ["ex_007","ex_008","ex_009"]),
    ("g_004", "Артикли a / an / the", [
        "Артикль «a» ставится перед исчисляемым существительным в единственном числе, если оно начинается с согласного звука: «a book». «an» — перед гласным звуком: «an apple». «the» используется, когда речь идёт об уже известном, конкретном предмете: «The book on the table is mine.»"
    ], ["I have a car.", "She ate an apple.", "The sun is bright.", "Give me the pen, please."], ["ex_010","ex_011","ex_012"]),
    ("g_005", "Вопросы и отрицания", [
        "Чтобы задать вопрос в Present Simple, перед подлежащим ставится вспомогательный глагол «do» (или «does» для he/she/it): «Do you work?», «Does she work?». Для отрицания используется «don't» / «doesn't»: «I don't know.», «He doesn't like coffee.»"
    ], ["Do you speak English?", "Does he live here?", "I don't understand.", "She doesn't have a car."], ["ex_013","ex_014","ex_015"]),
    ("g_006", "There is / There are", [
        "Конструкция «there is» (единственное число) и «there are» (множественное число) используется, чтобы сказать о наличии чего-либо: «There is a book on the table.» — Есть книга на столе. «There are two chairs.» — Есть два стула. Отрицание: «there isn't» / «there aren't»."
    ], ["There is a bank near my house.", "There are five people in my family.", "There isn't any milk.", "Is there a pharmacy near here?"], ["ex_016","ex_017","ex_018"]),
    ("g_007", "Can / Can't", [
        "Модальный глагол «can» означает «могу / умею» и используется для способности или разрешения: «I can swim.» Отрицание — «cannot» или «can't»: «I can't drive.» В вопросах «can» ставится перед подлежащим: «Can you help me?»"
    ], ["I can speak English.", "She can't come today.", "Can you help me, please?", "We can meet tomorrow."], ["ex_019","ex_020","ex_021"]),
    ("g_008", "Предлоги места", [
        "Предлоги места показывают, где находится предмет: in (в), on (на), under (под), next to (рядом с), between (между), behind (позади), in front of (перед). Пример: «The keys are on the table.» — Ключи на столе."
    ], ["The cat is under the table.", "The bank is next to the store.", "I live in an apartment.", "The car is in front of the house."], ["ex_022","ex_023","ex_024"]),
    ("g_009", "Предлоги времени", [
        "Предлоги времени: in — для месяцев, годов, времён года (in July, in 2024); on — для дней недели и дат (on Monday); at — для точного времени (at five o'clock). Пример: «I work on Monday at nine o'clock.»"
    ], ["My birthday is in June.", "I have a meeting on Friday.", "The shop opens at nine.", "We go on vacation in summer."], ["ex_025","ex_026","ex_027"]),
]

# (id, type, grammarId, prompt, options-or-None, correctAnswer)
EXERCISES = [
    ("ex_001","fill_blank","g_001","I ___ a teacher.", ["am","is","are"], "am"),
    ("ex_002","fill_blank","g_001","She ___ happy.", ["am","is","are"], "is"),
    ("ex_003","fill_blank","g_001","They ___ my friends.", ["am","is","are"], "are"),
    ("ex_004","choose_translation","g_002","Это моя книга. (This is ___ book.)", ["my","his","their"], "my"),
    ("ex_005","fill_blank","g_002","___ is a doctor. (Он)", ["She","He","They"], "He"),
    ("ex_006","fill_blank","g_002","This is ___ phone. (её)", ["her","his","your"], "her"),
    ("ex_007","fill_blank","g_003","She ___ (work) in a bank.", ["work","works","working"], "works"),
    ("ex_008","fill_blank","g_003","I ___ (live) in New York.", ["live","lives","living"], "live"),
    ("ex_009","fill_blank","g_003","He ___ (drink) coffee every day.", ["drink","drinks","drinking"], "drinks"),
    ("ex_010","fill_blank","g_004","I have ___ apple.", ["a","an","the"], "an"),
    ("ex_011","fill_blank","g_004","She has ___ car.", ["a","an","the"], "a"),
    ("ex_012","fill_blank","g_004","Give me ___ pen on the table, please.", ["a","an","the"], "the"),
    ("ex_013","fill_blank","g_005","___ you speak English?", ["Do","Does","Are"], "Do"),
    ("ex_014","fill_blank","g_005","He ___ like coffee.", ["don't","doesn't","isn't"], "doesn't"),
    ("ex_015","fill_blank","g_005","___ she live here?", ["Do","Does","Is"], "Does"),
    ("ex_016","fill_blank","g_006","___ a bank near my house.", ["There is","There are","There am"], "There is"),
    ("ex_017","fill_blank","g_006","___ five people in my family.", ["There is","There are","There be"], "There are"),
    ("ex_018","fill_blank","g_006","___ any milk in the fridge.", ["There isn't","There aren't","There don't"], "There isn't"),
    ("ex_019","fill_blank","g_007","I ___ speak English.", ["can","cans","canning"], "can"),
    ("ex_020","fill_blank","g_007","She ___ come today.", ["can't","isn't","doesn't"], "can't"),
    ("ex_021","fill_blank","g_007","___ you help me, please?", ["Can","Do","Are"], "Can"),
    ("ex_022","fill_blank","g_008","The cat is ___ the table.", ["under","on","between"], "under"),
    ("ex_023","fill_blank","g_008","The bank is ___ the store.", ["next to","under","behind"], "next to"),
    ("ex_024","fill_blank","g_008","I live ___ an apartment.", ["in","on","at"], "in"),
    ("ex_025","fill_blank","g_009","My birthday is ___ June.", ["in","on","at"], "in"),
    ("ex_026","fill_blank","g_009","I have a meeting ___ Friday.", ["in","on","at"], "on"),
    ("ex_027","fill_blank","g_009","The shop opens ___ nine o'clock.", ["in","on","at"], "at"),
]

# (id, situation, [(speaker, en, ru), ...])
DIALOGUES = [
    ("d_001", "Знакомство", [
        ("A","Hello! My name is Anna.","Привет! Меня зовут Анна."),
        ("B","Hi, Anna! I'm Mark. Nice to meet you.","Привет, Анна! Я Марк. Приятно познакомиться."),
        ("A","Nice to meet you too. Where are you from?","Мне тоже приятно познакомиться. Ты откуда?"),
        ("B","I'm from Poland. And you?","Я из Польши. А ты?"),
        ("A","I'm from Russia. I live in Chicago now.","Я из России. Сейчас я живу в Чикаго."),
        ("B","Great! See you around.","Отлично! Увидимся."),
    ]),
    ("d_002", "В магазине", [
        ("A","Excuse me, how much is this shirt?","Извините, сколько стоит эта рубашка?"),
        ("B","It's twenty dollars.","Она стоит двадцать долларов."),
        ("A","Do you have a smaller size?","У вас есть размер поменьше?"),
        ("B","Yes, here you are.","Да, вот, пожалуйста."),
        ("A","Great, I'll take it. Can I pay by card?","Отлично, я возьму её. Можно расплатиться картой?"),
        ("B","Of course. Here is your receipt.","Конечно. Вот ваш чек."),
    ]),
    ("d_003", "В ресторане", [
        ("A","Good evening! Can I see the menu, please?","Добрый вечер! Можно меню, пожалуйста?"),
        ("B","Of course. Are you ready to order?","Конечно. Вы готовы сделать заказ?"),
        ("A","Yes, I'd like a salad and a coffee, please.","Да, я хочу салат и кофе, пожалуйста."),
        ("B","Anything else?","Что-нибудь ещё?"),
        ("A","No, thank you. That's all.","Нет, спасибо. Это всё."),
        ("B","Okay, it will be ready soon.","Хорошо, скоро будет готово."),
    ]),
    ("d_004", "У врача", [
        ("A","Good morning. What's the problem?","Доброе утро. Что вас беспокоит?"),
        ("B","I have a headache and a fever.","У меня болит голова и температура."),
        ("A","How long have you felt sick?","Как долго вы себя плохо чувствуете?"),
        ("B","Since yesterday.","Со вчерашнего дня."),
        ("A","Take this medicine twice a day and drink water.","Принимайте это лекарство дважды в день и пейте воду."),
        ("B","Thank you, doctor.","Спасибо, доктор."),
    ]),
    ("d_005", "В аптеке", [
        ("A","Hello, I need medicine for a headache.","Здравствуйте, мне нужно лекарство от головной боли."),
        ("B","Do you have a prescription?","У вас есть рецепт?"),
        ("A","No, I don't. Is it necessary?","Нет. Это обязательно?"),
        ("B","No, this medicine doesn't need one.","Нет, для этого лекарства рецепт не нужен."),
        ("A","Great, how much is it?","Отлично, сколько это стоит?"),
        ("B","It's eight dollars.","Восемь долларов."),
    ]),
    ("d_006", "В DMV (получение прав)", [
        ("A","Hello, I need to renew my driver's license.","Здравствуйте, мне нужно продлить водительские права."),
        ("B","Do you have your ID and application form?","У вас есть удостоверение личности и заявление?"),
        ("A","Yes, here they are.","Да, вот они."),
        ("B","Please wait in line, number forty-two.","Пожалуйста, подождите в очереди, номер сорок два."),
        ("A","How long is the wait?","Сколько ждать?"),
        ("B","About twenty minutes.","Около двадцати минут."),
    ]),
    ("d_007", "В банке", [
        ("A","Hello, I'd like to open a bank account.","Здравствуйте, я хочу открыть банковский счёт."),
        ("B","Sure, do you have your passport and address?","Конечно, у вас есть паспорт и адрес?"),
        ("A","Yes, here you are.","Да, вот, пожалуйста."),
        ("B","Please fill out this form and sign here.","Пожалуйста, заполните эту форму и распишитесь здесь."),
        ("A","Is there a fee for the account?","Есть ли плата за счёт?"),
        ("B","No, this account is free.","Нет, этот счёт бесплатный."),
    ]),
    ("d_008", "Как пройти (направления)", [
        ("A","Excuse me, where is the nearest pharmacy?","Извините, где ближайшая аптека?"),
        ("B","Go straight and turn left at the corner.","Идите прямо и поверните налево на углу."),
        ("A","Is it far from here?","Это далеко отсюда?"),
        ("B","No, it's next to the bank, about five minutes.","Нет, это рядом с банком, минут пять."),
        ("A","Thank you very much!","Большое спасибо!"),
        ("B","You're welcome!","Пожалуйста!"),
    ]),
]

def build():
    words = []
    topics_out = []
    wid = 1
    for topic_id, title, grammar_ids, entries in TOPICS:
        word_ids = []
        for en, ru, pos, exEn, exRu in entries:
            wid_str = "w_%03d" % wid
            words.append({
                "id": wid_str, "en": en, "ru": ru, "partOfSpeech": pos,
                "topic": topic_id, "exampleEn": exEn, "exampleRu": exRu
            })
            word_ids.append(wid_str)
            wid += 1
        topics_out.append({"id": topic_id, "title": title, "words": word_ids, "grammar": grammar_ids})

    # sanity: no duplicate english headwords
    seen = {}
    for w in words:
        key = w["en"].lower()
        if key in seen:
            raise SystemExit("Duplicate en word: %s (%s and %s)" % (w["en"], seen[key], w["id"]))
        seen[key] = w["id"]

    grammar_out = []
    for gid, title, expl, examples, exIds in GRAMMAR:
        grammar_out.append({"id": gid, "title": title, "explanationRu": expl[0], "examples": examples, "exerciseIds": exIds})

    exercises_out = []
    for exid, typ, gid, prompt, options, correct in EXERCISES:
        item = {"id": exid, "type": typ, "wordIds": [], "grammarId": gid, "prompt": prompt, "correctAnswer": correct}
        if options: item["options"] = options
        exercises_out.append(item)

    dialogues_out = []
    for did, situation, lines in DIALOGUES:
        dialogues_out.append({
            "id": did, "situation": situation,
            "lines": [{"speaker": s, "en": en, "ru": ru} for s, en, ru in lines]
        })

    data = {
        "level": "A1",
        "title": "Начальный уровень",
        "passingThreshold": 0.9,
        "topics": topics_out,
        "words": words,
        "grammar": grammar_out,
        "exercises": exercises_out,
        "dialogues": dialogues_out,
        "examPool": [e["id"] for e in exercises_out],
    }
    return data

if __name__ == "__main__":
    data = build()
    out_path = os.path.join(os.path.dirname(__file__), "..", "data", "a1.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print("Written", out_path)
    print("Words:", len(data["words"]))
    print("Topics:", len(data["topics"]))
    print("Grammar:", len(data["grammar"]))
    print("Exercises:", len(data["exercises"]))
    print("Dialogues:", len(data["dialogues"]))
