#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Генератор data/a2.json — модуль уровня A2.
ID продолжают нумерацию с A1, чтобы не пересекаться (прогресс хранится
в единой localStorage-структуре по всему приложению):
words: w_538+, grammar: g_010+, exercises: ex_028+, dialogues: d_010+.
Запуск: python3 tools/gen_a2.py
"""
import json, os

WORD_ID_START = 538
GRAMMAR_ID_START = 10
EXERCISE_ID_START = 28
DIALOGUE_ID_START = 10

# (topic_id, title_ru, [grammar_ids], [(en, ru, pos, exampleEn, exampleRu), ...])
TOPICS = [
("work_detailed", "Работа (подробнее)", ["g_014"], [
    ("occupation", "профессия", "noun", "What is your occupation?", "Кем вы работаете?"),
    ("career", "карьера", "noun", "She has a good career.", "У неё хорошая карьера."),
    ("apply for a job", "подавать заявку на работу", "phrase", "I applied for a job online.", "Я подал заявку на работу онлайн."),
    ("promotion", "повышение", "noun", "He got a promotion last month.", "Он получил повышение в прошлом месяце."),
    ("deadline", "крайний срок", "noun", "The deadline is Friday.", "Крайний срок — пятница."),
    ("project", "проект", "noun", "We finished the project on time.", "Мы закончили проект вовремя."),
    ("client", "клиент (деловой)", "noun", "I have a meeting with a client.", "У меня встреча с клиентом."),
    ("remote work", "удалённая работа", "phrase", "I do remote work now.", "Сейчас я работаю удалённо."),
    ("overtime", "сверхурочные", "noun", "I worked overtime yesterday.", "Вчера я работал сверхурочно."),
    ("vacation days", "отпускные дни", "phrase", "I have ten vacation days.", "У меня десять отпускных дней."),
    ("sick leave", "больничный", "noun", "She is on sick leave.", "Она на больничном."),
    ("paycheck", "зарплатный чек", "noun", "I got my paycheck today.", "Сегодня я получил зарплату."),
    ("raise", "прибавка к зарплате", "noun", "I asked for a raise.", "Я попросил прибавку к зарплате."),
    ("quit", "уволиться (по своей воле)", "verb", "He quit his job.", "Он уволился с работы."),
    ("retire", "выйти на пенсию", "verb", "My father retired last year.", "Мой отец вышел на пенсию в прошлом году."),
    ("professional", "профессиональный", "adjective", "She is a professional cook.", "Она профессиональный повар."),
    ("skill", "навык", "noun", "Communication is an important skill.", "Общение — важный навык."),
    ("qualification", "квалификация", "noun", "Do you have the right qualifications?", "У вас есть нужная квалификация?"),
    ("degree", "учёная степень, диплом", "noun", "She has a degree in nursing.", "У неё диплом медсестры."),
    ("certificate", "сертификат", "noun", "I got a certificate for the course.", "Я получил сертификат за курс."),
    ("employer", "работодатель", "noun", "My employer is very fair.", "Мой работодатель очень справедливый."),
    ("supervisor", "руководитель, начальник", "noun", "My supervisor is helpful.", "Мой руководитель мне помогает."),
    ("warehouse", "склад", "noun", "He works in a warehouse.", "Он работает на складе."),
    ("factory", "фабрика, завод", "noun", "She works at a factory.", "Она работает на заводе."),
    ("construction", "строительство", "noun", "He works in construction.", "Он работает в строительстве."),
    ("teamwork", "командная работа", "noun", "Teamwork is important here.", "Здесь важна командная работа."),
    ("training", "обучение (на работе)", "noun", "New employees need training.", "Новым сотрудникам нужно обучение."),
    ("apply", "подавать заявление", "verb", "I want to apply for this position.", "Я хочу подать заявление на эту должность."),
    ("position", "должность", "noun", "This is a full-time position.", "Это должность на полную ставку."),
    ("duty", "обязанность", "noun", "Cleaning is one of my duties.", "Уборка — одна из моих обязанностей."),
    ("report", "отчёт", "noun", "I need to write a report.", "Мне нужно написать отчёт."),
    ("union", "профсоюз", "noun", "He is a member of a union.", "Он состоит в профсоюзе."),
    ("benefits", "льготы (на работе)", "noun", "This job has good benefits.", "На этой работе хорошие льготы."),
    ("freelance", "фриланс, внештатная работа", "adjective", "She works freelance.", "Она работает фрилансером."),
    ("license", "лицензия", "noun", "You need a license for this job.", "Для этой работы нужна лицензия."),
    ("minimum wage", "минимальная зарплата", "phrase", "The minimum wage went up.", "Минимальная зарплата выросла."),
    ("staff", "персонал", "noun", "The staff is very friendly.", "Персонал очень дружелюбный."),
]),
("housing", "Жильё", ["g_010"], [
    ("rent", "арендная плата", "noun", "The rent is $1,200 a month.", "Арендная плата — 1200 долларов в месяц."),
    ("to rent", "снимать, арендовать", "verb", "We want to rent an apartment.", "Мы хотим снять квартиру."),
    ("landlord", "арендодатель, хозяин жилья", "noun", "I called my landlord about the leak.", "Я позвонил хозяину квартиры насчёт протечки."),
    ("tenant", "арендатор, квартиросъёмщик", "noun", "The tenant pays rent every month.", "Арендатор платит аренду каждый месяц."),
    ("lease", "договор аренды", "noun", "I signed a one-year lease.", "Я подписал договор аренды на год."),
    ("security deposit", "залог (при аренде)", "noun", "I paid a security deposit.", "Я заплатил залог."),
    ("utilities", "коммунальные услуги", "noun", "Utilities are not included in the rent.", "Коммунальные услуги не включены в аренду."),
    ("neighbor", "сосед", "noun", "My neighbor is very quiet.", "Мой сосед очень тихий."),
    ("neighborhood", "район (жилой)", "noun", "This is a safe neighborhood.", "Это безопасный район."),
    ("move in", "переехать (въехать)", "phrase", "We move in next week.", "Мы въезжаем на следующей неделе."),
    ("move out", "съехать (выехать)", "phrase", "They are moving out soon.", "Они скоро съезжают."),
    ("furnished", "меблированный", "adjective", "The apartment is furnished.", "Квартира меблированная."),
    ("roommate", "сосед по квартире", "noun", "I have two roommates.", "У меня два соседа по квартире."),
    ("mortgage", "ипотека", "noun", "We are paying off our mortgage.", "Мы выплачиваем ипотеку."),
    ("own", "владеть", "verb", "They own their house.", "У них дом в собственности."),
    ("monthly payment", "ежемесячный платёж", "phrase", "The monthly payment is high.", "Ежемесячный платёж высокий."),
    ("maintenance", "обслуживание, ремонт (здания)", "noun", "The building has good maintenance.", "В здании хорошее обслуживание."),
    ("repair", "ремонт, чинить", "verb", "We need to repair the sink.", "Нам нужно починить раковину."),
    ("broken", "сломанный", "adjective", "The heater is broken.", "Обогреватель сломан."),
    ("plumber", "сантехник", "noun", "I called a plumber.", "Я вызвал сантехника."),
    ("electrician", "электрик", "noun", "The electrician fixed the lights.", "Электрик починил свет."),
    ("notice", "уведомление (о выезде)", "noun", "I gave 30 days notice.", "Я подал уведомление за 30 дней."),
    ("heating", "отопление", "noun", "The heating doesn't work.", "Отопление не работает."),
    ("air conditioning", "кондиционер (система)", "noun", "The air conditioning is broken.", "Кондиционер сломан."),
    ("elevator", "лифт", "noun", "The elevator is out of service.", "Лифт не работает."),
    ("balcony", "балкон", "noun", "We have a small balcony.", "У нас маленький балкон."),
    ("yard", "двор", "noun", "The kids play in the yard.", "Дети играют во дворе."),
    ("lease agreement", "договор аренды (документ)", "noun", "Read the lease agreement carefully.", "Внимательно прочитайте договор аренды."),
    ("studio apartment", "квартира-студия", "noun", "I live in a studio apartment.", "Я живу в квартире-студии."),
    ("building", "здание", "noun", "This building is very old.", "Это здание очень старое."),
    ("floor plan", "планировка", "noun", "I like the floor plan.", "Мне нравится планировка."),
    ("downtown", "центр города", "noun", "I live downtown.", "Я живу в центре города."),
    ("suburb", "пригород", "noun", "We live in the suburbs.", "Мы живём в пригороде."),
    ("lock", "замок", "noun", "Change the lock, please.", "Поменяйте замок, пожалуйста."),
    ("renovate", "делать ремонт (обновлять)", "verb", "We renovated the kitchen.", "Мы сделали ремонт на кухне."),
]),
("past_time", "Прошлое и время", ["g_010"], [
    ("ago", "назад (о времени)", "adverb", "I moved here two years ago.", "Я переехал сюда два года назад."),
    ("last week", "на прошлой неделе", "phrase", "I was sick last week.", "На прошлой неделе я болел."),
    ("last month", "в прошлом месяце", "phrase", "We traveled last month.", "Мы путешествовали в прошлом месяце."),
    ("last year", "в прошлом году", "phrase", "I graduated last year.", "Я закончил учёбу в прошлом году."),
    ("when I was", "когда я был", "phrase", "When I was young, I lived in Texas.", "Когда я был молодым, я жил в Техасе."),
    ("childhood", "детство", "noun", "I had a happy childhood.", "У меня было счастливое детство."),
    ("grow up", "расти, вырасти", "verb", "I grew up in a small town.", "Я вырос в маленьком городе."),
    ("was born", "родился", "phrase", "I was born in 1990.", "Я родился в 1990 году."),
    ("graduate", "закончить учёбу", "verb", "She graduated from college.", "Она закончила колледж."),
    ("already", "уже", "adverb", "I already ate lunch.", "Я уже пообедал."),
    ("just", "только что", "adverb", "I just finished my work.", "Я только что закончил работу."),
    ("once", "однажды, один раз", "adverb", "I visited Paris once.", "Я однажды был в Париже."),
    ("recently", "недавно", "adverb", "I moved recently.", "Я недавно переехал."),
    ("event", "событие", "noun", "It was an important event.", "Это было важное событие."),
    ("happen", "случаться, происходить", "verb", "What happened yesterday?", "Что случилось вчера?"),
    ("remember", "помнить, вспоминать", "verb", "I remember that day.", "Я помню тот день."),
    ("forget", "забывать", "verb", "I forgot my keys.", "Я забыл ключи."),
    ("past", "прошлое", "noun", "Let's not talk about the past.", "Давай не будем говорить о прошлом."),
    ("history", "история", "noun", "I like American history.", "Мне нравится американская история."),
    ("memory", "воспоминание, память", "noun", "I have good memories of that trip.", "У меня хорошие воспоминания об этой поездке."),
    ("used to", "раньше (делал что-то)", "phrase", "I used to live in Texas.", "Раньше я жил в Техасе."),
    ("decade", "десятилетие", "noun", "I lived there for a decade.", "Я жил там десять лет."),
    ("generation", "поколение", "noun", "My generation grew up with computers.", "Моё поколение выросло с компьютерами."),
]),
("future_plans", "Планы на будущее", ["g_012"], [
    ("plan", "план, планировать", "noun", "I have a plan for the weekend.", "У меня есть план на выходные."),
    ("goal", "цель", "noun", "My goal is to learn English.", "Моя цель — выучить английский."),
    ("dream", "мечта", "noun", "It's my dream to travel.", "Путешествовать — моя мечта."),
    ("dream about", "мечтать о", "phrase", "I dream about a new house.", "Я мечтаю о новом доме."),
    ("intend", "намереваться", "verb", "I intend to finish soon.", "Я намереваюсь закончить скоро."),
    ("future", "будущее", "noun", "I am excited about the future.", "Я рад будущему."),
    ("someday", "когда-нибудь", "adverb", "Someday I will visit Japan.", "Когда-нибудь я посещу Японию."),
    ("next week", "на следующей неделе", "phrase", "I start my new job next week.", "Я начинаю новую работу на следующей неделе."),
    ("next month", "в следующем месяце", "phrase", "We are moving next month.", "Мы переезжаем в следующем месяце."),
    ("soon", "скоро", "adverb", "I will call you soon.", "Я скоро тебе позвоню."),
    ("eventually", "в конце концов, со временем", "adverb", "Eventually, I will learn English well.", "Со временем я выучу английский хорошо."),
    ("decide", "решить, принять решение", "verb", "I decided to stay.", "Я решил остаться."),
    ("hope", "надеяться", "verb", "I hope to see you soon.", "Я надеюсь скоро увидеться."),
    ("expect", "ожидать", "verb", "I expect good news.", "Я ожидаю хороших новостей."),
    ("achieve", "достигать", "verb", "I want to achieve my goals.", "Я хочу достичь своих целей."),
    ("succeed", "преуспеть, добиться успеха", "verb", "She will succeed.", "У неё всё получится."),
    ("prepare", "готовиться", "verb", "I am preparing for the exam.", "Я готовлюсь к экзамену."),
    ("opportunity", "возможность", "noun", "This is a great opportunity.", "Это отличная возможность."),
    ("possible", "возможный", "adjective", "It is possible to change plans.", "Можно изменить планы."),
]),
("feelings_emotions", "Чувства и эмоции", [], [
    ("excited", "взволнованный (радостно)", "adjective", "I am excited about the trip.", "Я взволнован поездкой."),
    ("nervous", "нервничающий", "adjective", "I am nervous about the interview.", "Я нервничаю перед собеседованием."),
    ("worried", "обеспокоенный", "adjective", "She is worried about her son.", "Она беспокоится о сыне."),
    ("angry", "злой, сердитый", "adjective", "He is angry at me.", "Он злится на меня."),
    ("surprised", "удивлённый", "adjective", "I was surprised by the news.", "Я был удивлён новостью."),
    ("confused", "растерянный, сбитый с толку", "adjective", "I am confused about the schedule.", "Я запутался в расписании."),
    ("proud", "гордый", "adjective", "I am proud of you.", "Я горжусь тобой."),
    ("embarrassed", "смущённый", "adjective", "I felt embarrassed.", "Мне было неловко."),
    ("disappointed", "разочарованный", "adjective", "I am disappointed in the result.", "Я разочарован результатом."),
    ("relieved", "испытывающий облегчение", "adjective", "I am relieved it's over.", "Я рад, что это закончилось."),
    ("confident", "уверенный (в себе)", "adjective", "She feels confident.", "Она чувствует себя уверенно."),
    ("curious", "любопытный", "adjective", "I am curious about your job.", "Мне любопытна твоя работа."),
    ("bored", "скучающий", "adjective", "I am bored at home.", "Мне скучно дома."),
    ("lonely", "одинокий", "adjective", "He feels lonely sometimes.", "Иногда он чувствует себя одиноко."),
    ("grateful", "благодарный", "adjective", "I am grateful for your help.", "Я благодарен за твою помощь."),
    ("scared", "испуганный", "adjective", "The child is scared of the dark.", "Ребёнок боится темноты."),
    ("calm", "спокойный", "adjective", "Stay calm, please.", "Пожалуйста, оставайся спокойным."),
    ("upset", "расстроенный", "adjective", "She is upset about the news.", "Она расстроена новостью."),
    ("relaxed", "расслабленный", "adjective", "I feel relaxed on vacation.", "В отпуске я чувствую себя расслабленным."),
    ("stressed", "напряжённый, в стрессе", "adjective", "I am stressed about work.", "Я в стрессе из-за работы."),
    ("jealous", "завистливый, ревнивый", "adjective", "He is jealous of his brother.", "Он завидует брату."),
    ("disgusted", "испытывающий отвращение", "adjective", "I am disgusted by that smell.", "Мне противен этот запах."),
    ("feeling", "чувство", "noun", "Tell me your feelings.", "Расскажи мне о своих чувствах."),
    ("emotion", "эмоция", "noun", "It is hard to hide emotion.", "Трудно скрыть эмоцию."),
    ("mood", "настроение", "noun", "I am in a good mood.", "У меня хорошее настроение."),
    ("laugh", "смеяться", "verb", "We laughed all night.", "Мы смеялись всю ночь."),
    ("cry", "плакать", "verb", "The baby is crying.", "Ребёнок плачет."),
]),
("personality", "Черты характера", [], [
    ("friendly", "дружелюбный", "adjective", "My neighbor is very friendly.", "Мой сосед очень дружелюбный."),
    ("kind", "добрый", "adjective", "She is a kind person.", "Она добрый человек."),
    ("honest", "честный", "adjective", "He is always honest.", "Он всегда честен."),
    ("funny", "смешной, забавный", "adjective", "My brother is very funny.", "Мой брат очень смешной."),
    ("serious", "серьёзный", "adjective", "My boss is very serious.", "Мой начальник очень серьёзный."),
    ("shy", "застенчивый", "adjective", "The new student is shy.", "Новый ученик застенчивый."),
    ("polite", "вежливый", "adjective", "The staff is polite.", "Персонал вежливый."),
    ("rude", "грубый", "adjective", "It's rude to interrupt.", "Перебивать — грубо."),
    ("patient", "терпеливый", "adjective", "You need to be patient.", "Нужно быть терпеливым."),
    ("lazy", "ленивый", "adjective", "He is too lazy to cook.", "Ему слишком лень готовить."),
    ("hardworking", "трудолюбивый", "adjective", "She is very hardworking.", "Она очень трудолюбивая."),
    ("generous", "щедрый", "adjective", "My uncle is generous.", "Мой дядя щедрый."),
    ("smart", "умный", "adjective", "My daughter is very smart.", "Моя дочь очень умная."),
    ("creative", "творческий", "adjective", "He is a creative person.", "Он творческий человек."),
    ("brave", "смелый", "adjective", "The firefighter is brave.", "Пожарный смелый."),
    ("careful", "осторожный", "adjective", "Be careful on the road.", "Будь осторожен на дороге."),
    ("careless", "неосторожный, небрежный", "adjective", "Don't be careless with money.", "Не будь небрежным с деньгами."),
    ("selfish", "эгоистичный", "adjective", "He can be selfish sometimes.", "Иногда он бывает эгоистичным."),
    ("stubborn", "упрямый", "adjective", "My father is stubborn.", "Мой отец упрямый."),
    ("talkative", "разговорчивый", "adjective", "My sister is very talkative.", "Моя сестра очень разговорчивая."),
    ("optimistic", "оптимистичный", "adjective", "She is always optimistic.", "Она всегда оптимистична."),
    ("pessimistic", "пессимистичный", "adjective", "Don't be so pessimistic.", "Не будь таким пессимистом."),
    ("independent", "самостоятельный, независимый", "adjective", "My son is independent.", "Мой сын самостоятельный."),
    ("responsible", "ответственный", "adjective", "She is a responsible worker.", "Она ответственный работник."),
    ("character", "характер", "noun", "He has a strong character.", "У него сильный характер."),
    ("personality", "личность, характер", "noun", "She has a great personality.", "У неё отличный характер."),
]),
("opinions_comparisons", "Мнения и сравнения", ["g_013"], [
    ("better", "лучше", "adjective", "This phone is better.", "Этот телефон лучше."),
    ("worse", "хуже", "adjective", "The traffic is worse today.", "Сегодня пробки хуже."),
    ("best", "лучший", "adjective", "This is the best coffee shop.", "Это лучшая кофейня."),
    ("worst", "худший", "adjective", "That was the worst movie.", "Это был худший фильм."),
    ("more", "больше", "adverb", "This one is more expensive.", "Этот дороже."),
    ("less", "меньше", "adverb", "I eat less sugar now.", "Теперь я ем меньше сахара."),
    ("in my opinion", "по-моему, на мой взгляд", "phrase", "In my opinion, it's a good idea.", "По-моему, это хорошая идея."),
    ("I think that", "я думаю, что", "phrase", "I think that he is right.", "Я думаю, что он прав."),
    ("agree", "соглашаться", "verb", "I agree with you.", "Я согласен с тобой."),
    ("disagree", "не соглашаться", "verb", "I disagree with that.", "Я не согласен с этим."),
    ("prefer", "предпочитать", "verb", "I prefer tea to coffee.", "Я предпочитаю чай кофе."),
    ("compare", "сравнивать", "verb", "Let's compare the prices.", "Давай сравним цены."),
    ("similar", "похожий", "adjective", "These two houses are similar.", "Эти два дома похожи."),
    ("opinion", "мнение", "noun", "What is your opinion?", "Какое твоё мнение?"),
    ("than", "чем (при сравнении)", "conjunction", "She is taller than me.", "Она выше меня."),
    ("as...as", "так же... как", "phrase", "He is as tall as his father.", "Он такой же высокий, как его отец."),
    ("though", "хотя", "conjunction", "It's cheap, though it's good quality.", "Это дёшево, хотя качество хорошее."),
    ("however", "однако", "conjunction", "I like it, however it's expensive.", "Мне это нравится, однако это дорого."),
    ("depend on", "зависеть от", "phrase", "It depends on the weather.", "Это зависит от погоды."),
    ("matter", "иметь значение", "verb", "Your opinion matters to me.", "Твоё мнение важно для меня."),
]),
("phone_communication", "Телефон и связь", [], [
    ("phone call", "телефонный звонок", "noun", "I got a phone call.", "Мне позвонили."),
    ("answer the phone", "ответить на звонок", "phrase", "Please answer the phone.", "Пожалуйста, ответь на звонок."),
    ("hang up", "повесить трубку", "phrase", "She hung up quickly.", "Она быстро повесила трубку."),
    ("voicemail", "голосовая почта", "noun", "Leave a voicemail, please.", "Оставьте голосовое сообщение, пожалуйста."),
    ("text message", "смс-сообщение", "noun", "I sent a text message.", "Я отправил смс."),
    ("contact", "контакт", "noun", "Save this contact.", "Сохрани этот контакт."),
    ("missed call", "пропущенный звонок", "noun", "I have a missed call.", "У меня пропущенный звонок."),
    ("the line is busy", "линия занята", "phrase", "Sorry, the line is busy.", "Извините, линия занята."),
    ("hold on", "подождать (на линии)", "phrase", "Please hold on a moment.", "Пожалуйста, подождите минутку."),
    ("call back", "перезвонить", "phrase", "I will call you back.", "Я тебе перезвоню."),
    ("wrong number", "не тот номер", "phrase", "Sorry, wrong number.", "Извините, не туда попал."),
    ("area code", "код города/региона", "noun", "What is the area code?", "Какой код региона?"),
    ("extension", "добавочный номер", "noun", "Dial extension 205.", "Наберите добавочный 205."),
    ("signal", "сигнал (связи)", "noun", "There is no signal here.", "Здесь нет сигнала."),
    ("charge", "заряжать", "verb", "I need to charge my phone.", "Мне нужно зарядить телефон."),
    ("battery", "батарея, аккумулятор", "noun", "My battery is low.", "У меня разряжается батарея."),
    ("ring", "звонить (о звонке)", "verb", "The phone is ringing.", "Телефон звонит."),
    ("speak louder", "говорить громче", "phrase", "Can you speak louder?", "Можете говорить громче?"),
    ("repeat", "повторить", "verb", "Can you repeat that, please?", "Можете повторить, пожалуйста?"),
    ("connection", "связь, соединение", "noun", "The connection is bad.", "Связь плохая."),
    ("mute", "выключить звук", "verb", "Please mute your phone.", "Пожалуйста, выключите звук на телефоне."),
    ("available", "доступный, свободный", "adjective", "Is he available now?", "Он сейчас свободен?"),
    ("urgent", "срочный", "adjective", "This is urgent.", "Это срочно."),
    ("message", "сообщение", "noun", "I left you a message.", "Я оставил тебе сообщение."),
    ("reach", "связаться (с кем-то)", "verb", "I couldn't reach you.", "Я не смог с тобой связаться."),
]),
("technology", "Техника и интернет", [], [
    ("laptop", "ноутбук", "noun", "I work on my laptop.", "Я работаю за ноутбуком."),
    ("tablet", "планшет", "noun", "My daughter has a tablet.", "У моей дочери есть планшет."),
    ("charger", "зарядное устройство", "noun", "Do you have a charger?", "У тебя есть зарядка?"),
    ("wifi", "вайфай", "noun", "Is there free wifi here?", "Здесь есть бесплатный вайфай?"),
    ("internet", "интернет", "noun", "I need internet for work.", "Мне нужен интернет для работы."),
    ("app", "приложение", "noun", "I downloaded a new app.", "Я скачал новое приложение."),
    ("password", "пароль", "noun", "I forgot my password.", "Я забыл пароль."),
    ("screen", "экран", "noun", "The screen is broken.", "Экран разбит."),
    ("printer", "принтер", "noun", "The printer is out of paper.", "В принтере закончилась бумага."),
    ("camera", "камера, фотоаппарат", "noun", "My phone has a good camera.", "У моего телефона хорошая камера."),
    ("headphones", "наушники", "noun", "I listen to music with headphones.", "Я слушаю музыку в наушниках."),
    ("website", "веб-сайт", "noun", "Visit our website.", "Посетите наш сайт."),
    ("download", "скачивать", "verb", "Download the app first.", "Сначала скачай приложение."),
    ("upload", "загружать (в интернет)", "verb", "Upload the photo, please.", "Загрузи фото, пожалуйста."),
    ("click", "нажимать (мышью)", "verb", "Click this button.", "Нажми эту кнопку."),
    ("save", "сохранять", "verb", "Save the document.", "Сохрани документ."),
    ("delete", "удалять", "verb", "Delete this file.", "Удали этот файл."),
    ("update", "обновлять", "verb", "Update your app.", "Обнови своё приложение."),
    ("device", "устройство", "noun", "Turn off the device.", "Выключи устройство."),
    ("online", "онлайн", "adverb", "I shop online.", "Я делаю покупки онлайн."),
    ("search", "искать", "verb", "Search for the address online.", "Найди адрес онлайн."),
    ("social media", "социальные сети", "noun", "I don't use social media much.", "Я не особо пользуюсь соцсетями."),
    ("video", "видео", "noun", "Watch this video.", "Посмотри это видео."),
    ("settings", "настройки", "noun", "Check the settings.", "Проверь настройки."),
]),
("travel_vacation", "Путешествия и отпуск", [], [
    ("vacation", "отпуск, каникулы", "noun", "We are on vacation.", "Мы в отпуске."),
    ("trip", "поездка", "noun", "We had a great trip.", "У нас была отличная поездка."),
    ("hotel", "отель", "noun", "We stayed at a nice hotel.", "Мы остановились в хорошем отеле."),
    ("reservation", "бронирование", "noun", "I made a reservation.", "Я сделал бронирование."),
    ("luggage", "багаж", "noun", "My luggage is heavy.", "Мой багаж тяжёлый."),
    ("suitcase", "чемодан", "noun", "Pack your suitcase.", "Собери чемодан."),
    ("tourist", "турист", "noun", "There are many tourists here.", "Здесь много туристов."),
    ("sightseeing", "осмотр достопримечательностей", "noun", "We went sightseeing.", "Мы ходили смотреть достопримечательности."),
    ("souvenir", "сувенир", "noun", "I bought a souvenir.", "Я купил сувенир."),
    ("flight", "рейс, полёт", "noun", "Our flight is delayed.", "Наш рейс задерживается."),
    ("boarding pass", "посадочный талон", "noun", "Show your boarding pass.", "Покажите посадочный талон."),
    ("check in", "регистрация (на рейс/в отель)", "phrase", "We need to check in.", "Нам нужно зарегистрироваться."),
    ("customs", "таможня", "noun", "We went through customs.", "Мы прошли таможню."),
    ("guide", "гид, экскурсовод", "noun", "Our guide spoke English.", "Наш гид говорил по-английски."),
    ("beach", "пляж", "noun", "We relaxed on the beach.", "Мы отдыхали на пляже."),
    ("mountain", "гора", "noun", "We hiked in the mountains.", "Мы ходили в поход в горы."),
    ("lake", "озеро", "noun", "The lake is beautiful.", "Озеро красивое."),
    ("island", "остров", "noun", "We visited a small island.", "Мы посетили маленький остров."),
    ("abroad", "за границей, за границу", "adverb", "I want to travel abroad.", "Я хочу путешествовать за границу."),
    ("destination", "пункт назначения", "noun", "What is your destination?", "Какой у вас пункт назначения?"),
    ("itinerary", "маршрут поездки", "noun", "Here is our itinerary.", "Вот наш маршрут."),
    ("delay", "задержка", "noun", "There is a delay.", "Есть задержка."),
    ("cancel", "отменять", "verb", "They canceled the flight.", "Они отменили рейс."),
    ("pack", "собирать вещи (в дорогу)", "verb", "I need to pack.", "Мне нужно собрать вещи."),
    ("explore", "исследовать", "verb", "We explored the city.", "Мы исследовали город."),
    ("local", "местный", "adjective", "We ate at a local restaurant.", "Мы ели в местном ресторане."),
    ("foreign", "иностранный", "adjective", "I like foreign food.", "Мне нравится иностранная еда."),
    ("crowded", "переполненный, людный", "adjective", "The beach was crowded.", "Пляж был переполнен."),
    ("adventure", "приключение", "noun", "It was a great adventure.", "Это было отличное приключение."),
    ("memorable", "запоминающийся", "adjective", "It was a memorable trip.", "Это была запоминающаяся поездка."),
]),
("quantities", "Количества", ["g_015"], [
    ("a few", "несколько (с исч.)", "phrase", "I have a few friends here.", "У меня здесь несколько друзей."),
    ("a little", "немного (с неисч.)", "phrase", "I need a little help.", "Мне нужна небольшая помощь."),
    ("several", "несколько, несколько штук", "determiner", "I called several times.", "Я звонил несколько раз."),
    ("enough", "достаточно", "adverb", "Is this enough money?", "Этого денег достаточно?"),
    ("too much", "слишком много (с неисч.)", "phrase", "That's too much sugar.", "Это слишком много сахара."),
    ("too many", "слишком много (с исч.)", "phrase", "There are too many people.", "Здесь слишком много людей."),
    ("plenty of", "много, достаточно", "phrase", "We have plenty of time.", "У нас достаточно времени."),
    ("most of", "большинство", "determiner", "Most of my friends work here.", "Большинство моих друзей работают здесь."),
    ("none", "никто, ничего (из)", "pronoun", "None of them called.", "Никто из них не позвонил."),
    ("all", "все, весь", "determiner", "All the seats are taken.", "Все места заняты."),
    ("each", "каждый", "determiner", "Each person gets one ticket.", "Каждый получает один билет."),
    ("every", "каждый (из всех)", "determiner", "Every day I go to work.", "Каждый день я хожу на работу."),
    ("half", "половина", "noun", "I ate half the pizza.", "Я съел половину пиццы."),
    ("whole", "весь, целый", "adjective", "I read the whole book.", "Я прочитал всю книгу."),
    ("extra", "дополнительный", "adjective", "Can I get extra cheese?", "Можно мне дополнительный сыр?"),
]),
("verbs_a2", "Дополнительные глаголы", ["g_016"], [
    ("choose", "выбирать", "verb", "Choose one option.", "Выбери один вариант."),
    ("promise", "обещать", "verb", "I promise to help.", "Я обещаю помочь."),
    ("borrow", "брать взаймы", "verb", "Can I borrow your pen?", "Можно взять твою ручку?"),
    ("lend", "давать взаймы", "verb", "Can you lend me $10?", "Можешь одолжить мне 10 долларов?"),
    ("share", "делиться", "verb", "Let's share the pizza.", "Давай поделим пиццу."),
    ("complain", "жаловаться", "verb", "She complained about the noise.", "Она пожаловалась на шум."),
    ("apologize", "извиняться", "verb", "I apologize for being late.", "Извиняюсь за опоздание."),
    ("forgive", "прощать", "verb", "Please forgive me.", "Пожалуйста, прости меня."),
    ("invite", "приглашать", "verb", "I invited my friends.", "Я пригласил друзей."),
    ("join", "присоединяться", "verb", "Join us for dinner.", "Присоединяйся к нам на ужин."),
    ("avoid", "избегать", "verb", "I avoid sugar.", "Я избегаю сахара."),
    ("suggest", "предлагать (идею)", "verb", "I suggest we leave early.", "Предлагаю выйти пораньше."),
    ("recommend", "рекомендовать", "verb", "I recommend this restaurant.", "Рекомендую этот ресторан."),
    ("warn", "предупреждать", "verb", "She warned me about the traffic.", "Она предупредила меня о пробках."),
    ("explain", "объяснять", "verb", "Can you explain this word?", "Можешь объяснить это слово?"),
    ("discuss", "обсуждать", "verb", "Let's discuss the plan.", "Давайте обсудим план."),
    ("argue", "спорить", "verb", "They argued about money.", "Они спорили из-за денег."),
    ("allow", "разрешать", "verb", "They don't allow pets here.", "Здесь не разрешают домашних животных."),
    ("forbid", "запрещать", "verb", "Smoking is forbidden here.", "Здесь запрещено курить."),
    ("lose", "терять", "verb", "I lost my wallet.", "Я потерял кошелёк."),
    ("find", "находить", "verb", "I found my keys.", "Я нашёл ключи."),
    ("fix", "чинить, исправлять", "verb", "Can you fix this?", "Можешь это починить?"),
    ("break", "ломать", "verb", "Don't break the glass.", "Не разбей стакан."),
    ("build", "строить", "verb", "They are building a house.", "Они строят дом."),
    ("grow", "расти, выращивать", "verb", "The plant is growing fast.", "Растение быстро растёт."),
    ("push", "толкать", "verb", "Push the door.", "Толкни дверь."),
    ("pull", "тянуть", "verb", "Pull the handle.", "Потяни за ручку."),
    ("carry", "нести", "verb", "Can you carry this bag?", "Можешь понести эту сумку?"),
    ("throw", "бросать", "verb", "Throw me the ball.", "Брось мне мяч."),
    ("catch", "ловить", "verb", "Catch the ball!", "Поймай мяч!"),
    ("hold", "держать", "verb", "Hold my hand.", "Держи меня за руку."),
    ("touch", "трогать", "verb", "Don't touch that.", "Не трогай это."),
    ("hurt", "причинять боль, болеть", "verb", "My back hurts.", "У меня болит спина."),
    ("save money", "копить деньги, экономить", "phrase", "I try to save money.", "Я стараюсь экономить деньги."),
    ("spend", "тратить", "verb", "I spend too much on coffee.", "Я трачу слишком много на кофе."),
    ("waste", "тратить впустую", "verb", "Don't waste your time.", "Не трать время впустую."),
    ("earn", "зарабатывать", "verb", "I earn a good salary.", "Я зарабатываю хорошую зарплату."),
    ("owe", "быть должным (деньги)", "verb", "I owe you $20.", "Я должен тебе 20 долларов."),
    ("unlock", "отпирать", "verb", "Unlock the door, please.", "Отопри дверь, пожалуйста."),
    ("continue", "продолжать", "verb", "Please continue.", "Пожалуйста, продолжайте."),
    ("follow", "следовать", "verb", "Follow me, please.", "Следуй за мной, пожалуйста."),
]),
("adjectives_a2", "Дополнительные прилагательные", [], [
    ("comfortable", "удобный", "adjective", "This chair is comfortable.", "Этот стул удобный."),
    ("uncomfortable", "неудобный", "adjective", "These shoes are uncomfortable.", "Эта обувь неудобная."),
    ("convenient", "удобный (по расположению/времени)", "adjective", "The location is convenient.", "Расположение удобное."),
    ("dangerous", "опасный", "adjective", "This road is dangerous.", "Эта дорога опасная."),
    ("safe", "безопасный", "adjective", "This neighborhood is safe.", "Этот район безопасный."),
    ("successful", "успешный", "adjective", "She is a successful lawyer.", "Она успешный юрист."),
    ("popular", "популярный", "adjective", "This restaurant is popular.", "Этот ресторан популярный."),
    ("famous", "известный", "adjective", "He is a famous actor.", "Он известный актёр."),
    ("wealthy", "состоятельный, богатый", "adjective", "They are a wealthy family.", "Это состоятельная семья."),
    ("modern", "современный", "adjective", "The kitchen is modern.", "Кухня современная."),
    ("traditional", "традиционный", "adjective", "We ate traditional food.", "Мы ели традиционную еду."),
    ("various", "разные, разнообразные", "adjective", "The store has various products.", "В магазине разные товары."),
    ("common", "обычный, распространённый", "adjective", "This is a common problem.", "Это распространённая проблема."),
    ("rare", "редкий", "adjective", "This bird is rare.", "Эта птица редкая."),
    ("impossible", "невозможный", "adjective", "It's impossible to finish today.", "Невозможно закончить сегодня."),
    ("necessary", "необходимый", "adjective", "Water is necessary for life.", "Вода необходима для жизни."),
    ("unnecessary", "ненужный", "adjective", "This step is unnecessary.", "Этот шаг ненужен."),
    ("useful", "полезный", "adjective", "This app is useful.", "Это приложение полезное."),
    ("useless", "бесполезный", "adjective", "This tool is useless.", "Этот инструмент бесполезен."),
    ("huge", "огромный", "adjective", "It's a huge house.", "Это огромный дом."),
    ("tiny", "крошечный", "adjective", "The kitten is tiny.", "Котёнок крошечный."),
    ("wide", "широкий", "adjective", "The street is wide.", "Улица широкая."),
    ("narrow", "узкий", "adjective", "The hallway is narrow.", "Коридор узкий."),
    ("deep", "глубокий", "adjective", "The lake is deep.", "Озеро глубокое."),
    ("shallow", "мелкий (неглубокий)", "adjective", "The pool is shallow here.", "Здесь бассейн мелкий."),
    ("sharp", "острый", "adjective", "Be careful, the knife is sharp.", "Осторожно, нож острый."),
    ("smooth", "гладкий", "adjective", "The road is smooth.", "Дорога гладкая."),
    ("rough", "шершавый, грубый (о поверхности)", "adjective", "The wood feels rough.", "Дерево на ощупь шершавое."),
]),
("places_community", "Общественные места", [], [
    ("library", "библиотека", "noun", "I borrowed a book from the library.", "Я взял книгу в библиотеке."),
    ("gym", "спортзал", "noun", "I go to the gym every morning.", "Я хожу в спортзал каждое утро."),
    ("park", "парк", "noun", "We walked in the park.", "Мы гуляли в парке."),
    ("church", "церковь", "noun", "They go to church on Sunday.", "Они ходят в церковь по воскресеньям."),
    ("mosque", "мечеть", "noun", "The mosque is downtown.", "Мечеть находится в центре города."),
    ("temple", "храм", "noun", "We visited a beautiful temple.", "Мы посетили красивый храм."),
    ("museum", "музей", "noun", "The museum is closed on Monday.", "Музей закрыт по понедельникам."),
    ("theater", "театр, кинотеатр", "noun", "We watched a play at the theater.", "Мы смотрели спектакль в театре."),
    ("mall", "торговый центр", "noun", "Let's go to the mall.", "Давай сходим в торговый центр."),
    ("salon", "салон (красоты)", "noun", "She got her hair done at the salon.", "Она сделала причёску в салоне."),
    ("laundromat", "прачечная самообслуживания", "noun", "I wash my clothes at the laundromat.", "Я стираю вещи в прачечной."),
    ("post office", "почта", "noun", "I need to go to the post office.", "Мне нужно на почту."),
    ("police station", "полицейский участок", "noun", "The police station is nearby.", "Полицейский участок рядом."),
    ("fire station", "пожарная станция", "noun", "The fire station is on Elm Street.", "Пожарная станция на Элм-стрит."),
    ("city hall", "мэрия", "noun", "You can register at city hall.", "Зарегистрироваться можно в мэрии."),
    ("community center", "общественный центр", "noun", "There is a class at the community center.", "В общественном центре проходят занятия."),
    ("playground", "детская площадка", "noun", "The kids are at the playground.", "Дети на детской площадке."),
    ("parking lot", "парковка (место)", "noun", "The parking lot is full.", "Парковка заполнена."),
    ("sidewalk", "тротуар", "noun", "Walk on the sidewalk.", "Иди по тротуару."),
    ("block", "квартал", "noun", "The store is two blocks away.", "Магазин в двух кварталах отсюда."),
    ("square", "площадь (городская)", "noun", "We met at the square.", "Мы встретились на площади."),
    ("crosswalk", "пешеходный переход", "noun", "Use the crosswalk.", "Пользуйся пешеходным переходом."),
    ("public", "общественный", "adjective", "This is a public park.", "Это общественный парк."),
    ("local government", "местные власти", "noun", "The local government helps residents.", "Местные власти помогают жителям."),
    ("resident", "житель", "noun", "Every resident got a letter.", "Каждый житель получил письмо."),
    ("community", "сообщество", "noun", "Our community is very friendly.", "Наше сообщество очень дружелюбное."),
]),
("health_a2", "Здоровье (подробнее)", [], [
    ("specialist", "специалист (врач)", "noun", "You need to see a specialist.", "Вам нужно к специалисту."),
    ("surgery", "операция", "noun", "She had surgery last month.", "В прошлом месяце ей сделали операцию."),
    ("treatment", "лечение", "noun", "The treatment worked well.", "Лечение прошло хорошо."),
    ("diagnosis", "диагноз", "noun", "The doctor gave a diagnosis.", "Врач поставил диагноз."),
    ("vaccine", "вакцина", "noun", "I got a flu vaccine.", "Я сделал прививку от гриппа."),
    ("insurance card", "страховая карта", "noun", "Bring your insurance card.", "Возьмите свою страховую карту."),
    ("copay", "доплата (за приём врача)", "noun", "The copay is $20.", "Доплата — 20 долларов."),
    ("refill", "повторный рецепт (лекарства)", "noun", "I need a refill on my prescription.", "Мне нужно продлить рецепт."),
    ("emergency room", "приёмный покой", "noun", "We went to the emergency room.", "Мы поехали в приёмный покой."),
    ("urgent care", "неотложная помощь (клиника)", "noun", "Urgent care is open now.", "Клиника неотложной помощи сейчас открыта."),
    ("physical exam", "медицинский осмотр", "noun", "I need a physical exam.", "Мне нужен медосмотр."),
    ("blood pressure", "кровяное давление", "noun", "My blood pressure is normal.", "У меня нормальное давление."),
    ("weight", "вес", "noun", "The doctor checked my weight.", "Врач проверил мой вес."),
    ("height", "рост", "noun", "What is your height?", "Какой у тебя рост?"),
    ("diet", "диета, питание", "noun", "I am on a diet.", "Я на диете."),
    ("exercise", "физические упражнения", "noun", "Exercise is good for health.", "Физические упражнения полезны для здоровья."),
    ("rest", "отдых", "noun", "You need rest.", "Тебе нужен отдых."),
    ("injured", "раненый, травмированный", "adjective", "He is injured.", "Он травмирован."),
    ("recover", "выздоравливать", "verb", "I hope you recover soon.", "Надеюсь, ты скоро поправишься."),
    ("pregnant", "беременная", "adjective", "My sister is pregnant.", "Моя сестра беременна."),
    ("diabetes", "диабет", "noun", "He has diabetes.", "У него диабет."),
    ("asthma", "астма", "noun", "She has asthma.", "У неё астма."),
    ("allergic", "аллергичный", "adjective", "I am allergic to peanuts.", "У меня аллергия на арахис."),
    ("side effect", "побочный эффект", "noun", "This medicine has side effects.", "У этого лекарства есть побочные эффекты."),
    ("dose", "доза", "noun", "Take one dose in the morning.", "Принимайте одну дозу утром."),
]),
("money_finance", "Деньги и финансы", ["g_015"], [
    ("budget", "бюджет", "noun", "We have a family budget.", "У нас семейный бюджет."),
    ("income", "доход", "noun", "My income increased this year.", "Мой доход вырос в этом году."),
    ("expense", "расход", "noun", "Rent is my biggest expense.", "Аренда — мой самый большой расход."),
    ("bill", "счёт (к оплате)", "noun", "I need to pay this bill.", "Мне нужно оплатить этот счёт."),
    ("debt", "долг", "noun", "I have some debt.", "У меня есть долг."),
    ("loan", "кредит, заём", "noun", "We took out a loan.", "Мы взяли кредит."),
    ("interest rate", "процентная ставка", "noun", "The interest rate is high.", "Процентная ставка высокая."),
    ("credit score", "кредитный рейтинг", "noun", "A good credit score helps you.", "Хороший кредитный рейтинг помогает."),
    ("tax", "налог", "noun", "I pay tax every year.", "Я плачу налоги каждый год."),
    ("ATM", "банкомат", "noun", "There is an ATM nearby.", "Рядом есть банкомат."),
    ("check", "чек (банковский)", "noun", "I paid by check.", "Я заплатил чеком."),
    ("transfer", "перевод (денег)", "noun", "I made a bank transfer.", "Я сделал банковский перевод."),
    ("savings", "сбережения", "noun", "I have some savings.", "У меня есть сбережения."),
    ("afford", "позволить себе (финансово)", "verb", "I can't afford that car.", "Я не могу себе позволить эту машину."),
    ("worth", "стоящий (о ценности)", "adjective", "This ring is worth a lot.", "Это кольцо стоит дорого."),
    ("value", "ценность, стоимость", "noun", "The house increased in value.", "Дом вырос в цене."),
    ("currency", "валюта", "noun", "What is the local currency?", "Какая здесь местная валюта."),
    ("exchange rate", "обменный курс", "noun", "The exchange rate changed.", "Обменный курс изменился."),
    ("invest", "инвестировать", "verb", "I want to invest my money.", "Я хочу инвестировать деньги."),
    ("refund", "возврат денег", "noun", "I got a refund.", "Мне вернули деньги."),
    ("overdue", "просроченный", "adjective", "This bill is overdue.", "Этот счёт просрочен."),
    ("financial", "финансовый", "adjective", "I need financial advice.", "Мне нужен финансовый совет."),
]),
("education", "Образование", [], [
    ("school", "школа", "noun", "My kids go to school.", "Мои дети ходят в школу."),
    ("college", "колледж", "noun", "She studies at college.", "Она учится в колледже."),
    ("university", "университет", "noun", "He graduated from university.", "Он закончил университет."),
    ("class", "урок, занятие", "noun", "The class starts at nine.", "Занятие начинается в девять."),
    ("teacher", "учитель, преподаватель", "noun", "My teacher is very patient.", "Мой преподаватель очень терпеливый."),
    ("student", "студент, ученик", "noun", "I am a student.", "Я студент."),
    ("lesson", "урок", "noun", "The lesson was interesting.", "Урок был интересным."),
    ("homework", "домашнее задание", "noun", "I finished my homework.", "Я закончил домашнее задание."),
    ("test", "тест, контрольная", "noun", "We have a test tomorrow.", "У нас завтра тест."),
    ("grade", "оценка", "noun", "She got a good grade.", "Она получила хорошую оценку."),
    ("exam", "экзамен", "noun", "I have an exam next week.", "У меня экзамен на следующей неделе."),
    ("subject", "предмет (учебный)", "noun", "Math is my favorite subject.", "Математика — мой любимый предмет."),
    ("diploma", "диплом", "noun", "She received her diploma.", "Она получила диплом."),
    ("scholarship", "стипендия", "noun", "He got a scholarship.", "Он получил стипендию."),
    ("tuition", "плата за обучение", "noun", "Tuition is expensive.", "Плата за обучение высокая."),
    ("enroll", "записаться (на курс)", "verb", "I enrolled in an English class.", "Я записался на курс английского."),
    ("attend", "посещать (занятия)", "verb", "I attend classes twice a week.", "Я посещаю занятия дважды в неделю."),
    ("pass", "сдать (экзамен)", "verb", "I passed the exam.", "Я сдал экзамен."),
    ("fail", "провалить (экзамен)", "verb", "I failed my first test.", "Я провалил свой первый тест."),
    ("knowledge", "знание", "noun", "He has a lot of knowledge.", "У него много знаний."),
    ("practice", "практика", "noun", "Practice makes perfect.", "Практика ведёт к совершенству."),
    ("improve", "улучшать(ся)", "verb", "I want to improve my English.", "Я хочу улучшить свой английский."),
]),
("shopping_appearance_a2", "Одежда, внешность и покупки (доп.)", [], [
    ("try on", "примерить", "phrase", "Can I try this on?", "Можно это примерить?"),
    ("fit", "подходить (по размеру)", "verb", "These shoes don't fit.", "Эта обувь не подходит."),
    ("fitting room", "примерочная", "noun", "Where is the fitting room?", "Где примерочная?"),
    ("exchange", "обменять (товар)", "verb", "I want to exchange this shirt.", "Я хочу обменять эту рубашку."),
    ("return", "вернуть (товар)", "verb", "I want to return this.", "Я хочу это вернуть."),
    ("appearance", "внешность", "noun", "Appearance isn't everything.", "Внешность — не главное."),
    ("handsome", "красивый (о мужчине)", "adjective", "He is handsome.", "Он красив."),
    ("pretty", "красивая, симпатичная", "adjective", "She is very pretty.", "Она очень красивая."),
    ("attractive", "привлекательный", "adjective", "That is an attractive design.", "Это привлекательный дизайн."),
    ("overweight", "с избыточным весом", "adjective", "The doctor said I am overweight.", "Врач сказал, что у меня избыточный вес."),
    ("skinny", "худой, худощавый", "adjective", "He is very skinny.", "Он очень худой."),
    ("bald", "лысый", "adjective", "My grandfather is bald.", "Мой дедушка лысый."),
    ("curly", "кудрявый", "adjective", "She has curly hair.", "У неё кудрявые волосы."),
    ("straight", "прямой (о волосах)", "adjective", "My hair is straight.", "У меня прямые волосы."),
    ("beard", "борода", "noun", "He has a beard.", "У него борода."),
    ("mustache", "усы", "noun", "My father has a mustache.", "У моего отца усы."),
    ("glasses", "очки", "noun", "I wear glasses.", "Я ношу очки."),
    ("jewelry", "украшения", "noun", "She likes jewelry.", "Ей нравятся украшения."),
    ("gold ring", "кольцо", "noun", "She wears a gold ring.", "Она носит золотое кольцо."),
    ("necklace", "ожерелье", "noun", "She got a necklace as a gift.", "Ей подарили ожерелье."),
    ("earrings", "серьги", "noun", "She is wearing earrings.", "На ней серьги."),
    ("wristwatch", "наручные часы", "noun", "He wears a nice wristwatch.", "Он носит красивые наручные часы."),
]),
("weather_nature_a2", "Природа и климат (доп.)", [], [
    ("nature", "природа", "noun", "I love spending time in nature.", "Я люблю проводить время на природе."),
    ("forest", "лес", "noun", "We walked through the forest.", "Мы гуляли по лесу."),
    ("river", "река", "noun", "The river is very long.", "Река очень длинная."),
    ("ocean", "океан", "noun", "The ocean is beautiful.", "Океан красивый."),
    ("desert", "пустыня", "noun", "It's very hot in the desert.", "В пустыне очень жарко."),
    ("climate", "климат", "noun", "The climate here is mild.", "Здесь мягкий климат."),
    ("storm", "шторм, буря", "noun", "A storm is coming.", "Приближается шторм."),
    ("thunder", "гром", "noun", "I heard thunder last night.", "Прошлой ночью я слышал гром."),
    ("lightning", "молния", "noun", "Lightning struck the tree.", "Молния ударила в дерево."),
    ("fog", "туман", "noun", "There is a lot of fog this morning.", "Сегодня утром сильный туман."),
    ("humid", "влажный (о погоде)", "adjective", "It's very humid today.", "Сегодня очень влажно."),
    ("freezing", "ледяной, очень холодный", "adjective", "It's freezing outside.", "На улице ужасно холодно."),
    ("forecast", "прогноз (погоды)", "noun", "The forecast says rain.", "Прогноз обещает дождь."),
    ("environment", "окружающая среда", "noun", "We should protect the environment.", "Нам следует беречь окружающую среду."),
    ("pollution", "загрязнение", "noun", "Air pollution is a problem.", "Загрязнение воздуха — это проблема."),
    ("recycle", "перерабатывать (отходы)", "verb", "We recycle paper and plastic.", "Мы перерабатываем бумагу и пластик."),
    ("plant", "растение", "noun", "I have many plants at home.", "У меня дома много растений."),
    ("wildlife", "дикая природа, животный мир", "noun", "The park protects wildlife.", "Парк защищает дикую природу."),
]),
("daily_routine_a2", "Распорядок дня (доп.)", [], [
    ("routine", "распорядок, рутина", "noun", "I have a morning routine.", "У меня есть утренний распорядок."),
    ("wake up", "просыпаться", "phrase", "I wake up at six.", "Я просыпаюсь в шесть."),
    ("get dressed", "одеваться", "phrase", "I get dressed quickly.", "Я быстро одеваюсь."),
    ("brush teeth", "чистить зубы", "phrase", "I brush my teeth twice a day.", "Я чищу зубы дважды в день."),
    ("take a shower", "принимать душ", "phrase", "I always take a shower before bed.", "Я всегда принимаю душ перед сном."),
    ("make the bed", "заправлять кровать", "phrase", "I make the bed every morning.", "Я заправляю кровать каждое утро."),
    ("commute", "добираться до работы", "verb", "My commute takes an hour.", "Дорога на работу занимает час."),
    ("errand", "поручение, дело (по хозяйству)", "noun", "I have errands to run.", "Мне нужно сделать несколько дел."),
    ("chore", "домашняя обязанность", "noun", "Doing chores takes time.", "Домашние дела занимают время."),
    ("laundry", "стирка, бельё", "noun", "I do laundry on Sundays.", "Я стираю по воскресеньям."),
    ("grocery shopping", "поход за продуктами", "noun", "I do grocery shopping weekly.", "Я хожу за продуктами раз в неделю."),
    ("relax", "расслабляться, отдыхать", "verb", "I relax after work.", "Я отдыхаю после работы."),
    ("nap", "вздремнуть", "noun", "I took a short nap.", "Я немного вздремнул."),
    ("alarm clock", "будильник", "noun", "My alarm clock didn't ring.", "Мой будильник не зазвонил."),
    ("habit", "привычка", "noun", "Reading is a good habit.", "Чтение — хорошая привычка."),
    ("in a hurry", "торопиться, спешить", "phrase", "I am in a hurry.", "Я тороплюсь."),
    ("on time", "вовремя", "phrase", "Please arrive on time.", "Пожалуйста, приходи вовремя."),
]),
("numbers_time_a2", "Числа и время (доп.)", [], [
    ("thousand", "тысяча", "number", "The city has ten thousand people.", "В городе десять тысяч человек."),
    ("million", "миллион", "number", "The company is worth a million dollars.", "Компания стоит миллион долларов."),
    ("quarter", "четверть", "noun", "It's a quarter past five.", "Сейчас четверть шестого."),
    ("percent", "процент", "noun", "Fifty percent of people agree.", "Пятьдесят процентов людей согласны."),
    ("century", "век, столетие", "noun", "This building is a century old.", "Этому зданию сто лет."),
    ("period", "период", "noun", "It was a difficult period.", "Это был трудный период."),
    ("approximately", "примерно", "adverb", "It costs approximately $50.", "Это стоит примерно 50 долларов."),
    ("exactly", "точно, ровно", "adverb", "It's exactly noon.", "Сейчас ровно полдень."),
    ("weekday", "будний день", "noun", "I work on weekdays.", "Я работаю по будним дням."),
    ("weekend", "выходные", "noun", "See you on the weekend.", "Увидимся на выходных."),
    ("holiday", "праздник, выходной", "noun", "Today is a holiday.", "Сегодня праздник."),
    ("anniversary", "годовщина", "noun", "Happy anniversary!", "С годовщиной!"),
    ("birthday", "день рождения", "noun", "My birthday is in May.", "Мой день рождения в мае."),
    ("era", "эпоха", "noun", "It was a different era.", "Это была другая эпоха."),
    ("moment", "момент", "noun", "Wait a moment.", "Подожди момент."),
]),
("driving_car_a2", "Вождение и автомобиль", [], [
    ("driver", "водитель", "noun", "The driver was careful.", "Водитель был осторожен."),
    ("passenger", "пассажир", "noun", "There are three passengers.", "Здесь три пассажира."),
    ("seatbelt", "ремень безопасности", "noun", "Put on your seatbelt.", "Пристегни ремень безопасности."),
    ("speed limit", "ограничение скорости", "noun", "The speed limit is 30.", "Ограничение скорости — 30."),
    ("traffic", "трафик, движение (дорожное)", "noun", "The traffic is heavy today.", "Сегодня сильный трафик."),
    ("traffic jam", "пробка", "noun", "We were stuck in a traffic jam.", "Мы застряли в пробке."),
    ("highway", "шоссе, автомагистраль", "noun", "Take the highway.", "Поезжай по шоссе."),
    ("lane", "полоса (движения)", "noun", "Stay in your lane.", "Держись своей полосы."),
    ("traffic ticket", "штраф за нарушение", "noun", "I got a traffic ticket.", "Я получил штраф."),
    ("gas", "бензин", "noun", "I need to buy gas.", "Мне нужно купить бензин."),
    ("tank", "бак (топливный)", "noun", "The tank is empty.", "Бак пуст."),
    ("flat tire", "спущенное колесо", "noun", "I have a flat tire.", "У меня спустило колесо."),
    ("mechanic", "автомеханик", "noun", "The mechanic fixed my car.", "Автомеханик починил мою машину."),
    ("car insurance", "автостраховка", "noun", "I need car insurance.", "Мне нужна автостраховка."),
    ("registration", "регистрация (авто)", "noun", "My registration expired.", "Моя регистрация истекла."),
    ("pull over", "остановиться (у обочины)", "phrase", "The police asked me to pull over.", "Полиция попросила меня остановиться."),
    ("park the car", "парковать(ся)", "verb", "I parked the car near the store.", "Я припарковался рядом с магазином."),
    ("reverse", "задний ход", "noun", "Put the car in reverse.", "Включи задний ход."),
    ("brake", "тормоз", "noun", "Press the brake.", "Нажми на тормоз."),
    ("steering wheel", "руль", "noun", "Hold the steering wheel.", "Держи руль."),
    ("honk", "сигналить (клаксоном)", "verb", "Don't honk, please.", "Не сигналь, пожалуйста."),
]),
("dining_out_a2", "В ресторане (подробнее)", [], [
    ("waiter", "официант", "noun", "The waiter took our order.", "Официант принял наш заказ."),
    ("waitress", "официантка", "noun", "The waitress was friendly.", "Официантка была приветливой."),
    ("table for two", "столик на двоих", "phrase", "A table for two, please.", "Столик на двоих, пожалуйста."),
    ("order", "заказывать", "verb", "I would like to order now.", "Я хотел бы сделать заказ сейчас."),
    ("appetizer", "закуска", "noun", "We ordered an appetizer.", "Мы заказали закуску."),
    ("main course", "основное блюдо", "noun", "What is the main course?", "Какое основное блюдо?"),
    ("dessert", "десерт", "noun", "Let's order dessert.", "Давай закажем десерт."),
    ("tip", "чаевые", "noun", "We left a tip.", "Мы оставили чаевые."),
    ("spicy", "острый (о еде)", "adjective", "This soup is spicy.", "Этот суп острый."),
    ("fresh", "свежий", "adjective", "The fish is fresh.", "Рыба свежая."),
    ("vegetarian", "вегетарианец, вегетарианский", "adjective", "I am vegetarian.", "Я вегетарианец."),
    ("vegan", "веган, веганский", "adjective", "This dish is vegan.", "Это блюдо веганское."),
    ("takeout", "еда на вынос", "noun", "Can I get this as takeout?", "Можно это на вынос?"),
    ("delivery", "доставка", "noun", "Do you offer delivery?", "У вас есть доставка?"),
    ("portion", "порция", "noun", "The portion is big.", "Порция большая."),
    ("napkin", "салфетка", "noun", "Can I have a napkin?", "Можно салфетку?"),
    ("straw", "трубочка (для питья)", "noun", "Can I have a straw?", "Можно трубочку?"),
    ("check please", "счёт, пожалуйста", "phrase", "Check, please.", "Счёт, пожалуйста."),
]),
("relationships_a2", "Отношения", [], [
    ("boyfriend", "парень (возлюбленный)", "noun", "This is my boyfriend.", "Это мой парень."),
    ("girlfriend", "девушка (возлюбленная)", "noun", "He introduced his girlfriend.", "Он познакомил всех со своей девушкой."),
    ("fiance", "жених", "noun", "He is my fiance.", "Он мой жених."),
    ("engaged", "помолвлен(а)", "adjective", "We are engaged.", "Мы помолвлены."),
    ("divorced", "разведён(а)", "adjective", "They are divorced.", "Они в разводе."),
    ("single", "холост, не замужем", "adjective", "I am single.", "Я не женат."),
    ("widow", "вдова", "noun", "She is a widow.", "Она вдова."),
    ("widower", "вдовец", "noun", "He is a widower.", "Он вдовец."),
    ("stepmother", "мачеха", "noun", "My stepmother is kind.", "Моя мачеха добрая."),
    ("stepfather", "отчим", "noun", "My stepfather works nearby.", "Мой отчим работает неподалёку."),
    ("in-laws", "родственники со стороны супруга(и)", "noun", "My in-laws are visiting.", "Мои родственники со стороны мужа/жены в гостях."),
    ("niece", "племянница", "noun", "My niece is five.", "Моей племяннице пять лет."),
    ("nephew", "племянник", "noun", "My nephew loves soccer.", "Мой племянник любит футбол."),
    ("close", "близкий", "adjective", "We are close friends.", "Мы близкие друзья."),
    ("trust", "доверять", "verb", "I trust my friend.", "Я доверяю своему другу."),
    ("support", "поддерживать", "verb", "My family supports me.", "Моя семья меня поддерживает."),
    ("relationship", "отношения", "noun", "We have a good relationship.", "У нас хорошие отношения."),
    ("get along", "ладить", "phrase", "We get along well.", "Мы хорошо ладим."),
    ("miss", "скучать (по кому-то)", "verb", "I miss my family.", "Я скучаю по семье."),
    ("hug", "обнимать(ся)", "verb", "We hugged at the airport.", "Мы обнялись в аэропорту."),
]),
("everyday_extra_a2", "Ещё повседневные слова", [], [
    ("actually", "на самом деле", "adverb", "Actually, I disagree.", "На самом деле, я не согласен."),
    ("probably", "вероятно", "adverb", "It will probably rain.", "Вероятно, будет дождь."),
    ("maybe", "может быть", "adverb", "Maybe I will come.", "Может быть, я приду."),
    ("certainly", "конечно, определённо", "adverb", "I will certainly help.", "Я определённо помогу."),
    ("especially", "особенно", "adverb", "I like fruit, especially apples.", "Мне нравятся фрукты, особенно яблоки."),
    ("almost", "почти", "adverb", "I am almost done.", "Я почти закончил."),
    ("nearly", "почти, около", "adverb", "It's nearly six o'clock.", "Уже почти шесть."),
    ("suddenly", "внезапно", "adverb", "Suddenly it started to rain.", "Внезапно пошёл дождь."),
    ("finally", "наконец", "adverb", "Finally, I finished the report.", "Наконец я закончил отчёт."),
    ("immediately", "немедленно", "adverb", "Call me immediately.", "Позвони мне немедленно."),
    ("instead", "вместо (этого)", "adverb", "Let's go there instead.", "Давай пойдём туда вместо этого."),
    ("anyway", "в любом случае", "adverb", "Anyway, let's continue.", "В любом случае, продолжим."),
    ("somewhere", "где-то", "adverb", "I left it somewhere.", "Я оставил это где-то."),
    ("nowhere", "нигде", "adverb", "There is nowhere to sit.", "Здесь негде сесть."),
    ("everywhere", "везде", "adverb", "I looked everywhere.", "Я искал везде."),
    ("anywhere", "где угодно, где-нибудь", "adverb", "You can sit anywhere.", "Можешь сесть где угодно."),
    ("someone", "кто-то", "pronoun", "Someone called you.", "Кто-то тебе звонил."),
    ("no one", "никто", "pronoun", "No one answered.", "Никто не ответил."),
    ("everyone", "все, каждый", "pronoun", "Everyone likes her.", "Она всем нравится."),
    ("anyone", "кто-нибудь, кто угодно", "pronoun", "Does anyone know?", "Кто-нибудь знает?"),
    ("something", "что-то", "pronoun", "I need something to drink.", "Мне нужно что-то попить."),
    ("nothing", "ничего", "pronoun", "There is nothing here.", "Здесь ничего нет."),
    ("everything", "всё", "pronoun", "Everything is fine.", "Всё в порядке."),
    ("anything", "что-нибудь, что угодно", "pronoun", "Do you need anything?", "Тебе что-нибудь нужно?"),
    ("either", "тоже (в отриц.), любой из двух", "adverb", "I don't like it either.", "Мне это тоже не нравится."),
    ("neither", "ни тот, ни другой", "determiner", "Neither option works.", "Ни один вариант не подходит."),
]),
]

GRAMMAR = [
    ("g_010", "Past Simple (простое прошедшее время)", [
        "Past Simple используется для завершённых действий в прошлом. Глагол «to be» имеет формы was (I/he/she/it) и were (you/we/they). Правильные глаголы получают окончание -ed: work → worked. Многие частотные глаголы неправильные и меняют форму полностью: go → went, have → had, see → saw. Вопросы и отрицания образуются с помощью did/didn't + базовая форма глагола: «Did you go?», «I didn't go»."
    ], ["I was at home yesterday.", "She worked late last night.", "We went to the park.", "Did you see that movie?", "I didn't call him."], ["ex_028","ex_029","ex_030"]),
    ("g_011", "Present Continuous (настоящее длительное время)", [
        "Present Continuous (be + глагол-ing) используется для действий, происходящих прямо сейчас, или временных ситуаций. Например: «I am working now» — я сейчас работаю. Не путайте с Present Simple, который описывает привычки: «I work every day» (обычно) и «I am working now» (сейчас)."
    ], ["I am reading a book right now.", "She is cooking dinner.", "They are watching TV.", "What are you doing?", "It is raining outside."], ["ex_031","ex_032","ex_033"]),
    ("g_012", "Будущее время: going to / will", [
        "«going to» используется для планов, которые вы уже решили: «I am going to visit my parents this weekend.» «will» используется для быстрых решений, обещаний и предсказаний: «I will call you later.», «It will rain tomorrow.»"
    ], ["I am going to start a new job.", "We are going to move next month.", "I will help you.", "She will be happy.", "Will you come to the party?"], ["ex_034","ex_035","ex_036"]),
    ("g_013", "Сравнительная и превосходная степень", [
        "Для коротких прилагательных добавляется -er/-est: cheap → cheaper → the cheapest. Для длинных прилагательных используются more/the most: expensive → more expensive → the most expensive. Сравнение двух предметов использует «than»: «This is cheaper than that.»"
    ], ["This apartment is bigger than mine.", "He is the tallest in his family.", "This job is more interesting than my old one.", "She is the most patient teacher."], ["ex_037","ex_038","ex_039"]),
    ("g_014", "Модальные глаголы should / must / have to", [
        "«should» — совет, «стоит сделать»: «You should call the landlord.» «must» и «have to» — обязанность, «должен»: «I have to pay rent on the first.» «must» чаще используется для строгих правил, «have to» — для повседневных обязанностей. Отрицание «don't have to» означает «не обязательно», а не запрет."
    ], ["You should see a doctor.", "I have to work tomorrow.", "You must wear a seatbelt.", "You don't have to come if you're busy."], ["ex_040","ex_041","ex_042"]),
    ("g_015", "Some / any / much / many / a lot of", [
        "«some» используется в утвердительных предложениях (some water, some apples), «any» — в вопросах и отрицаниях (Do you have any money? I don't have any time). «much» — с неисчисляемыми существительными (much money), «many» — с исчисляемыми (many friends). «a lot of» подходит для обоих типов."
    ], ["I have some questions.", "Do you have any experience?", "I don't have much time.", "How many people work here?", "We have a lot of work today."], ["ex_043","ex_044","ex_045"]),
    ("g_016", "Местоимения-дополнения (object pronouns)", [
        "Местоимения-дополнения (me, you, him, her, it, us, them) используются после глагола или предлога, вместо подлежащего: I → me, he → him, she → her, we → us, they → them. Например: «Call me.», «I saw her yesterday.», «Give it to them.»"
    ], ["Can you help me?", "I called him yesterday.", "She gave it to us.", "Please tell them the news."], ["ex_046","ex_047","ex_048"]),
]

# (id, type, grammarId, prompt, options-or-None, correctAnswer)
EXERCISES = [
    ("ex_028","fill_blank","g_010","I ___ (be) at home yesterday.", ["was","were","am"], "was"),
    ("ex_029","fill_blank","g_010","She ___ (work) late last night.", ["work","worked","working"], "worked"),
    ("ex_030","fill_blank","g_010","___ you see that movie?", ["Did","Do","Was"], "Did"),
    ("ex_031","fill_blank","g_011","I ___ (read) a book right now.", ["read","am reading","reads"], "am reading"),
    ("ex_032","fill_blank","g_011","She ___ (cook) dinner.", ["is cooking","cooks","cook"], "is cooking"),
    ("ex_033","fill_blank","g_011","What ___ you doing?", ["are","is","do"], "are"),
    ("ex_034","fill_blank","g_012","I ___ start a new job next month. (уже решено)", ["am going to","will","am"], "am going to"),
    ("ex_035","fill_blank","g_012","It's cold, I ___ close the window. (быстрое решение)", ["am going to","will","am"], "will"),
    ("ex_036","fill_blank","g_012","___ you come to the party?", ["Will","Do","Are"], "Will"),
    ("ex_037","fill_blank","g_013","This apartment is ___ (big) than mine.", ["bigger","more big","biggest"], "bigger"),
    ("ex_038","fill_blank","g_013","He is the ___ (tall) in his family.", ["taller","tallest","more tall"], "tallest"),
    ("ex_039","fill_blank","g_013","This job is ___ (interesting) than my old one.", ["more interesting","interestinger","most interesting"], "more interesting"),
    ("ex_040","fill_blank","g_014","You ___ see a doctor. (совет)", ["should","must","can"], "should"),
    ("ex_041","fill_blank","g_014","I ___ work tomorrow. (обязанность)", ["have to","should","can"], "have to"),
    ("ex_042","fill_blank","g_014","You ___ wear a seatbelt. (строгое правило)", ["must","should","can"], "must"),
    ("ex_043","fill_blank","g_015","I have ___ questions.", ["some","any","much"], "some"),
    ("ex_044","fill_blank","g_015","Do you have ___ experience?", ["some","any","much"], "any"),
    ("ex_045","fill_blank","g_015","How ___ people work here?", ["much","many","some"], "many"),
    ("ex_046","fill_blank","g_016","Can you help ___? (я)", ["I","me","my"], "me"),
    ("ex_047","fill_blank","g_016","I called ___ yesterday. (он)", ["he","him","his"], "him"),
    ("ex_048","fill_blank","g_016","She gave it to ___. (мы)", ["we","us","our"], "us"),
]

# (id, situation, [(speaker, en, ru), ...])
DIALOGUES = [
    ("d_010", "Собеседование на работу", [
        ("A","Thank you for coming in today. Tell me about your work experience.","Спасибо, что пришли сегодня. Расскажите о своём опыте работы."),
        ("B","I worked as a cashier for two years.","Я два года работал кассиром."),
        ("A","Why do you want this job?","Почему вы хотите получить эту работу?"),
        ("B","I am hardworking, and I want to learn new skills.","Я трудолюбивый, и хочу освоить новые навыки."),
        ("A","Great. When can you start?","Отлично. Когда вы можете начать?"),
        ("B","I can start next week.","Я могу начать на следующей неделе."),
    ]),
    ("d_011", "Разговор с арендодателем", [
        ("A","Hi, the heating in my apartment is broken.","Здравствуйте, у меня в квартире сломано отопление."),
        ("B","I'm sorry to hear that. I will send someone today.","Мне жаль это слышать. Я сегодня же кого-нибудь пришлю."),
        ("A","Thank you. Also, when is the rent due?","Спасибо. И ещё, когда нужно платить аренду?"),
        ("B","Rent is due on the first of the month.","Аренду нужно платить первого числа месяца."),
        ("A","Okay, got it.","Хорошо, понятно."),
        ("B","Let me know if you need anything else.","Дайте знать, если понадобится что-то ещё."),
    ]),
    ("d_012", "Разговор о прошлых выходных", [
        ("A","How was your weekend?","Как прошли твои выходные?"),
        ("B","It was great! I visited my parents.","Отлично! Я навестил родителей."),
        ("A","What did you do there?","Что вы там делали?"),
        ("B","We cooked dinner and watched a movie.","Мы приготовили ужин и посмотрели фильм."),
        ("A","That sounds nice.","Звучит здорово."),
        ("B","Yes, it was very relaxing.","Да, это было очень расслабляюще."),
    ]),
    ("d_013", "Планы на будущее", [
        ("A","What are your plans for next year?","Какие у тебя планы на следующий год?"),
        ("B","I am going to look for a new job.","Я собираюсь искать новую работу."),
        ("A","That's exciting! What kind of job?","Здорово! Какую работу?"),
        ("B","Something in technology, I hope.","Надеюсь, что-то в сфере технологий."),
        ("A","I hope it works out for you.","Надеюсь, у тебя всё получится."),
        ("B","Thank you!","Спасибо!"),
    ]),
    ("d_014", "Жалоба на шум", [
        ("A","Excuse me, could you turn down the music? It's very loud.","Извините, не могли бы вы сделать музыку потише? Очень громко."),
        ("B","Oh, I'm sorry. I didn't realize it was so late.","Ой, извините. Я не заметил, что уже так поздно."),
        ("A","No problem, I just have to work early tomorrow.","Ничего страшного, просто мне рано на работу завтра."),
        ("B","I understand. I will turn it down now.","Понимаю. Сейчас сделаю тише."),
        ("A","Thank you, I appreciate it.","Спасибо, я это ценю."),
        ("B","Have a good night.","Спокойной ночи."),
    ]),
    ("d_015", "Запись к специалисту", [
        ("A","Hello, I need to make an appointment with a specialist.","Здравствуйте, мне нужно записаться к специалисту."),
        ("B","What is the problem?","В чём проблема?"),
        ("A","I have pain in my back.","У меня болит спина."),
        ("B","The doctor is available on Thursday at 3 PM.","Врач свободен в четверг в 15:00."),
        ("A","That works for me.","Мне подходит."),
        ("B","Great, see you then.","Отлично, до встречи."),
    ]),
]

# (id, situation, [line, ...]) — line is ("caller", en, ru) or ("you", [(en,ru,correct), ...])
CALLS = [
    ("call_001", "Звонок от арендодателя", [
        ("caller","Hello, this is your landlord. Is this a good time to talk?","Здравствуйте, это ваш арендодатель. Сейчас удобно говорить?"),
        ("you",[("Yes, of course.","Да, конечно.",True), ("I don't have an apartment.","У меня нет квартиры.",False)]),
        ("caller","Your lease ends next month. Do you want to renew it?","Ваш договор аренды заканчивается в следующем месяце. Хотите продлить?"),
        ("you",[("Yes, I would like to renew it.","Да, я хотел бы продлить.",True), ("I like pizza.","Мне нравится пицца.",False)]),
        ("caller","Great. The new rent will be $1,300 a month.","Отлично. Новая арендная плата будет 1300 долларов в месяц."),
        ("you",[("Okay, that works for me.","Хорошо, меня это устраивает.",True), ("I am from Russia.","Я из России.",False)]),
        ("caller","Perfect. I will send you the new contract.","Отлично. Я пришлю вам новый договор."),
    ]),
    ("call_002", "Звонок от работодателя", [
        ("caller","Hi, this is Karen from ABC Company. Is this Ivan?","Здравствуйте, это Карен из компании ABC. Это Иван?"),
        ("you",[("Yes, this is Ivan.","Да, это Иван.",True), ("No, thank you.","Нет, спасибо.",False)]),
        ("caller","We would like to offer you the position. Are you still interested?","Мы хотели бы предложить вам эту должность. Вам всё ещё интересно?"),
        ("you",[("Yes, I am very interested.","Да, мне очень интересно.",True), ("I don't know you.","Я вас не знаю.",False)]),
        ("caller","Great. Can you start on Monday?","Отлично. Вы можете начать в понедельник?"),
        ("you",[("Yes, Monday works for me.","Да, понедельник мне подходит.",True), ("The weather is nice today.","Сегодня хорошая погода.",False)]),
        ("caller","Wonderful. Welcome to the team!","Замечательно. Добро пожаловать в команду!"),
    ]),
    ("call_003", "Звонок из поликлиники", [
        ("caller","Hello, this is the clinic calling to confirm your appointment tomorrow at 10 AM.","Здравствуйте, это звонок из клиники, чтобы подтвердить ваш приём завтра в 10 утра."),
        ("you",[("Yes, I will be there.","Да, я приду.",True), ("I like coffee.","Мне нравится кофе.",False)]),
        ("caller","Great. Please bring your insurance card.","Отлично. Пожалуйста, возьмите вашу страховую карту."),
        ("you",[("Okay, I will bring it.","Хорошо, я возьму её.",True), ("I am going to the beach.","Я еду на пляж.",False)]),
        ("caller","Also, please arrive 15 minutes early.","И, пожалуйста, приходите на 15 минут раньше."),
        ("you",[("No problem, I will be early.","Без проблем, я приду пораньше.",True), ("I don't have a car.","У меня нет машины.",False)]),
        ("caller","Perfect, see you tomorrow!","Отлично, до завтра!"),
    ]),
]

def build():
    words = []
    topics_out = []
    wid = WORD_ID_START
    for topic_id, title, grammar_ids, entries in TOPICS:
        word_ids = []
        for en, ru, pos, exEn, exRu in entries:
            wid_str = "w_%03d" % wid
            words.append({
                "id": wid_str, "en": en, "ru": ru, "partOfSpeech": pos,
                "topic": topic_id, "exampleEn": exEn, "exampleRu": exRu
            })
            word_ids.append(wid_str)
            wid += 1
        topics_out.append({"id": topic_id, "title": title, "words": word_ids, "grammar": grammar_ids})

    seen = {}
    for w in words:
        key = w["en"].lower()
        if key in seen:
            raise SystemExit("Duplicate en word: %s (%s and %s)" % (w["en"], seen[key], w["id"]))
        seen[key] = w["id"]

    grammar_out = []
    for gid, title, expl, examples, exIds in GRAMMAR:
        grammar_out.append({"id": gid, "title": title, "explanationRu": expl[0], "examples": examples, "exerciseIds": exIds})

    exercises_out = []
    for exid, typ, gid, prompt, options, correct in EXERCISES:
        item = {"id": exid, "type": typ, "wordIds": [], "grammarId": gid, "prompt": prompt, "correctAnswer": correct}
        if options: item["options"] = options
        exercises_out.append(item)

    dialogues_out = []
    for did, situation, lines in DIALOGUES:
        dialogues_out.append({
            "id": did, "situation": situation,
            "lines": [{"speaker": s, "en": en, "ru": ru} for s, en, ru in lines]
        })

    calls_out = []
    for cid, situation, lines in CALLS:
        out_lines = []
        for line in lines:
            if line[0] == "caller":
                out_lines.append({"speaker": "caller", "en": line[1], "ru": line[2]})
            else:
                opts = [{"en": en, "ru": ru, "correct": correct} for en, ru, correct in line[1]]
                out_lines.append({"speaker": "you", "options": opts})
        calls_out.append({"id": cid, "situation": situation, "lines": out_lines})

    data = {
        "level": "A2",
        "title": "Элементарный уровень",
        "passingThreshold": 0.9,
        "topics": topics_out,
        "words": words,
        "grammar": grammar_out,
        "exercises": exercises_out,
        "dialogues": dialogues_out,
        "calls": calls_out,
        "examPool": [e["id"] for e in exercises_out],
    }
    return data

if __name__ == "__main__":
    data = build()
    out_path = os.path.join(os.path.dirname(__file__), "..", "data", "a2.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print("Written", out_path)
    print("Words:", len(data["words"]), "(ids %s..%s)" % (data["words"][0]["id"], data["words"][-1]["id"]))
    print("Topics:", len(data["topics"]))
    print("Grammar:", len(data["grammar"]))
    print("Exercises:", len(data["exercises"]))
    print("Dialogues:", len(data["dialogues"]))
    print("Calls:", len(data["calls"]))
